/**
 * ADOPTION_SCHEMAS · 当前集合写回策略登记。
 *
 * 单例表走 FIELD_REGISTRY 定位记录;集合表必须在这里登记 identity / 去重 /
 * 自动盖章 / FK 校验策略。
 */
import type { AdoptionExtensionSpec, CollectionAdoptionSpec } from './types'
import { REGISTRY_BY_NAME } from './project-tables'

const ADOPTION_SCHEMAS_RAW: CollectionAdoptionSpec[] = [
  {
    target: 'projects',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
  },
  {
    target: 'worlds',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
  },
  {
    target: 'works',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'world',
  },
  {
    target: 'adaptationProjects',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'screenplayScenes',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'comicPages',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'comicPanels',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'comicVisualSubjects',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'storyCores',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['projectId', 'workId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'creativeRules',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'error',
    required: [],
    autoStamps: ['projectId', 'workId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'worldGroups',
    identity: 'name',
    duplicatePolicy: 'error',
    required: ['name', 'type', 'description', 'icon', 'order', 'entryCondition', 'powerRestriction', 'plannedChapterCount'],
    autoStamps: ['projectId', 'worldId', 'createdAt', 'updatedAt'],
    ownerFrom: 'world',
  },
  {
    target: 'characters',
    identity: { kind: 'composite', fields: ['homeWorldGroupId', 'name'] },
    duplicatePolicy: 'merge',
    required: ['name', 'roleWeight', 'moralAxis', 'orderAxis'],
    autoStamps: ['projectId', 'homeWorldGroupId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'characterRelations',
    identity: {
      kind: 'composite',
      fields: ['fromCharacterId', 'toCharacterId', 'relationType'],
    },
    duplicatePolicy: 'skip',
    required: ['fromCharacterId', 'toCharacterId', 'relationType', 'label', 'isBidirectional'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'fromCharacterId', target: 'characters' },
      { field: 'toCharacterId', target: 'characters' },
    ],
  },
  {
    target: 'foreshadows',
    identity: 'name',
    duplicatePolicy: 'merge',
    required: ['name', 'type', 'status', 'description'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'plantChapterId', target: 'chapters' },
      { field: 'resolveChapterId', target: 'chapters' },
      { field: 'expectedResolveChapterId', target: 'chapters' },
    ],
  },
  {
    target: 'outlineNodes',
    identity: { kind: 'composite', fields: ['parentId', 'type', 'title'] },
    duplicatePolicy: 'skip',
    required: ['type', 'title'],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    fkChecks: [{ field: 'parentId', target: 'outlineNodes' }],
  },
  {
    target: 'chapters',
    identity: { kind: 'composite', fields: ['outlineNodeId', 'title'] },
    duplicatePolicy: 'update',
    required: ['outlineNodeId', 'title'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
    fkChecks: [
      { field: 'outlineNodeId', target: 'outlineNodes' },
      { field: 'perspectiveCharacterId', target: 'characters' },
    ],
  },
  {
    target: 'detailedOutlines',
    identity: { kind: 'composite', fields: ['outlineNodeId'] },
    duplicatePolicy: 'update',
    required: ['outlineNodeId'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
    fkChecks: [{ field: 'outlineNodeId', target: 'outlineNodes' }],
    arrayMemberChecks: [
      { field: 'appearingCharacterIds', itemTarget: 'characters' },
      { field: 'foreshadowIds', itemTarget: 'foreshadows' },
    ],
  },
  {
    target: 'emotionBeatCards',
    identity: { kind: 'composite', fields: ['chapterId'] },
    duplicatePolicy: 'update',
    required: ['chapterId', 'chapterTitle', 'overallArc', 'beats', 'source'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
    fkChecks: [{ field: 'chapterId', target: 'chapters' }],
  },
  {
    target: 'storyArcs',
    identity: 'name',
    duplicatePolicy: 'merge',
    required: ['name', 'type'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'storylineProgress',
    identity: { kind: 'composite', fields: ['arcId'] },
    duplicatePolicy: 'update',
    required: ['arcId', 'status', 'progressNote', 'involvedEntities'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'arcId', target: 'storyArcs' },
      { field: 'lastActiveChapterId', target: 'chapters' },
    ],
  },
  {
    target: 'storylineCrossings',
    identity: { kind: 'composite', fields: ['arcIdA', 'arcIdB', 'chapterId'] },
    duplicatePolicy: 'update',
    required: ['arcIdA', 'arcIdB', 'note', 'evidenceQuote'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'arcIdA', target: 'storyArcs' },
      { field: 'arcIdB', target: 'storyArcs' },
      { field: 'chapterId', target: 'chapters' },
    ],
  },
  {
    target: 'codexCategories',
    identity: { kind: 'composite', fields: ['domain', 'parentId', 'name'] },
    duplicatePolicy: 'skip',
    required: ['domain', 'name'],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    fkChecks: [{ field: 'parentId', target: 'codexCategories' }],
  },
  {
    target: 'codexEntries',
    identity: { kind: 'composite', fields: ['worldGroupId', 'categoryId', 'name'] },
    duplicatePolicy: 'merge',
    required: ['categoryId', 'name'],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'categoryId', target: 'codexCategories' },
      { field: 'importantLocationId', target: 'importantLocations' },
    ],
  },
  {
    target: 'cultivationSystems',
    identity: { kind: 'composite', fields: ['worldGroupId', 'name'] },
    duplicatePolicy: 'merge',
    required: ['name', 'description', 'stages'],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'cultivationProgress',
    identity: {
      kind: 'composite',
      fields: ['characterId', 'sourceChapterId', 'stageId', 'sourceQuote'],
    },
    duplicatePolicy: 'skip',
    required: [
      'characterId', 'characterName', 'cultivationSystemId', 'cultivationSystemName',
      'stageId', 'stageName', 'transition', 'sourceChapterId', 'sourceChapterTitle',
      'sourceQuote', 'sourceOffset', 'status',
    ],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'characterId', target: 'characters' },
      { field: 'cultivationSystemId', target: 'cultivationSystems' },
      { field: 'sourceChapterId', target: 'chapters' },
    ],
  },
  {
    target: 'importantLocations',
    identity: 'name',
    duplicatePolicy: 'merge',
    required: ['name'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [{ field: 'parentId', target: 'importantLocations' }],
  },
  {
    target: 'worldNodes',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    ownerFrom: 'world',
  },
  {
    target: 'itemLedger',
    identity: { kind: 'composite', fields: ['chapterId', 'itemName', 'action', 'heldByName', 'note'] },
    duplicatePolicy: 'skip',
    required: ['itemName', 'action', 'quantity', 'heldByName'],
    autoStamps: ['projectId', 'createdAt'],
    fkChecks: [{ field: 'chapterId', target: 'chapters' }, { field: 'characterId', target: 'characters' }],
    replaceScope: ['chapterId'],
  },
  {
    target: 'knowledgeLedger',
    identity: {
      kind: 'composite',
      fields: ['characterId', 'knowledgeKey', 'action', 'sourceChapterId', 'statement'],
    },
    duplicatePolicy: 'skip',
    required: ['characterName', 'knowledgeKey', 'statement', 'action', 'sourceType', 'status'],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
    fkChecks: [
      { field: 'characterId', target: 'characters' },
      { field: 'factId', target: 'temporalFacts' },
      { field: 'sourceChapterId', target: 'chapters' },
    ],
  },
  {
    target: 'storyTimelineEvents',
    identity: { kind: 'composite', fields: ['chapterId', 'title'] },
    duplicatePolicy: 'update',
    required: ['title', 'importance'],
    autoStamps: ['projectId', 'createdAt'],
    fkChecks: [{ field: 'chapterId', target: 'chapters' }],
    replaceScope: ['chapterId'],
  },
  {
    target: 'historicalTimelineEvents',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'historicalKeywords',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'worldGroupId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'stateCards',
    identity: { kind: 'composite', fields: ['category', 'entityName'] },
    duplicatePolicy: 'merge',
    required: ['category', 'entityName', 'fields'],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [{ field: 'lastChapterId', target: 'chapters' }],
  },
  {
    target: 'references',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
  },
  {
    target: 'referenceAnalysisRuns',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'createdAt', 'updatedAt'],
    fkChecks: [{ field: 'referenceId', target: 'references' }],
  },
  {
    target: 'characterDrivenPlans',
    identity: 'id',
    recordOnly: true,
    duplicatePolicy: 'update',
    required: [],
    autoStamps: ['projectId', 'workId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
  },
  {
    target: 'referenceChunkAnalysis',
    identity: { kind: 'composite', fields: ['analysisRunId', 'chunkIndex'] },
    duplicatePolicy: 'update',
    required: ['referenceId', 'analysisRunId', 'chunkIndex'],
    autoStamps: ['createdAt'],
    fkChecks: [
      { field: 'referenceId', target: 'references' },
      { field: 'analysisRunId', target: 'referenceAnalysisRuns' },
    ],
    replaceScope: ['analysisRunId'],
  },
  {
    target: 'ttrpgRulePacks',
    identity: { kind: 'composite', fields: ['ruleSystemId', 'ruleSystemVersion'] },
    duplicatePolicy: 'update',
    required: ['ruleSystemId', 'ruleSystemVersion', 'title', 'status', 'rulePackJson', 'contentHash'],
    autoStamps: ['projectId', 'worldId', 'workId', 'createdAt', 'updatedAt'],
    ownerFrom: 'work',
  },
]

export const ADOPTION_EXTENSIONS: readonly AdoptionExtensionSpec[] = Object.freeze([
  {
    id: 'reference-analysis-run-lifecycle',
    target: 'referenceAnalysisRuns',
    entrypoints: [
      'src/lib/reference-analysis/lifecycle.ts',
    ],
    policyRegistry: 'REFERENCE_ANALYSIS_RUN_POLICY + ADOPTION_SCHEMAS + PROJECT_TABLES',
    reason: '分析版本的创建、激活、回滚与裁剪必须在事务内维持唯一 active、来源声明不可变和既有版本不丢失；AI 派生字段更新仍走 adopt。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'reference-analysis-source-lifecycle',
    target: 'referenceAnalysisSources',
    entrypoints: ['src/lib/reference-analysis/lifecycle.ts'],
    policyRegistry: 'REFERENCE_ANALYSIS_RUN_POLICY + PROJECT_TABLES',
    reason: '本地原文只服务断点续跑，必须与 run 原子绑定和级联删除，且禁止进入项目 JSON 导出。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'reference-analysis-chunk-lifecycle',
    target: 'referenceChunkAnalysis',
    entrypoints: [
      'src/lib/reference-analysis/lifecycle.ts',
    ],
    policyRegistry: 'REFERENCE_ANALYSIS_RUN_POLICY + ADOPTION_SCHEMAS + PROJECT_TABLES',
    reason: '分块绑定 runId 以及版本/参考删除必须在领域事务内原子重映射或级联；新的 AI 分块写入仍统一走 adopt。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'reference-analysis-reference-lifecycle',
    target: 'references',
    entrypoints: ['src/lib/reference-analysis/lifecycle.ts'],
    policyRegistry: 'REFERENCE_ANALYSIS_RUN_POLICY + PROJECT_TABLES refs',
    reason: '激活版本需原子同步当前投影；删除参考需同时清理版本、分块、原文与创作规则引用。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'reference-analysis-citation-lifecycle',
    target: 'creativeRules',
    entrypoints: ['src/lib/reference-analysis/lifecycle.ts'],
    policyRegistry: 'PROJECT_TABLES references refs',
    reason: '删除参考时必须在同一事务移除 creativeRules.citedReferenceIds，避免 AI 上下文保留悬空引用。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'fact-ledger',
    target: 'temporalFacts',
    entrypoints: [
      'src/lib/fact-ledger/fact-ledger.ts',
      'src/lib/fact-ledger/human-readable-io.ts',
      'src/lib/fact-ledger/lifecycle.ts',
      'src/lib/fact-ledger/setting-assertions.ts',
      'src/lib/consistency/impact-analysis.ts',
      'src/lib/cultivation/lifecycle.ts',
      'src/lib/editor/entity-rename.ts',
    ],
    policyRegistry: 'FACT_PREDICATE_REGISTRY',
    reason: '事实候选需要谓词、时序、证据、确认与 supersede 领域约束；它是 adopt 的受控领域扩展，不是第二套通用写回层。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'character-merge-lifecycle',
    target: 'characters',
    entrypoints: [
      'src/lib/import/character-merge.ts',
      'src/lib/codex/references.ts',
      'src/lib/cultivation/lifecycle.ts',
      'src/lib/cultivation/progress-lifecycle.ts',
    ],
    policyRegistry: 'PROJECT_TABLES refs + remapCharacterReferences + cultivation DAG validator',
    reason: '角色合并及上游实体删除都需要在事务内重映射或置空跨表引用；普通角色新增和更新仍必须走 adopt。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'knowledge-ledger',
    target: 'knowledgeLedger',
    entrypoints: [
      'src/lib/knowledge-ledger/knowledge-ledger.ts',
      'src/lib/knowledge-ledger/lifecycle.ts',
    ],
    policyRegistry: 'KNOWLEDGE_ACTIONS + ADOPTION_SCHEMAS + PROJECT_TABLES',
    reason: '角色认知候选必须经人工确认，投影必须按规范章序和世界隔离计算；角色与章节删除还需要保留证据并降级复核。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'storyline-progress-lifecycle',
    target: 'storylineProgress',
    entrypoints: ['src/lib/storyline/lifecycle.ts'],
    policyRegistry: 'ADOPTION_SCHEMAS + PROJECT_TABLES refs',
    reason: '章节删除必须保留作者确认的进度与冗余章名并只断开 FK；故事线删除则必须在同一事务级联清理动态投影，无法由普通字段采纳表达。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'storyline-crossing-lifecycle',
    target: 'storylineCrossings',
    entrypoints: ['src/lib/storyline/lifecycle.ts'],
    policyRegistry: 'ADOPTION_SCHEMAS + PROJECT_TABLES refs',
    reason: '章节删除只断开交汇的章节 FK，故事线删除则级联清理所有相关交汇；这是受控删除生命周期，不是 AI 写回旁路。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'story-arc-dynamic-lifecycle',
    target: 'storyArcs',
    entrypoints: ['src/lib/storyline/lifecycle.ts'],
    policyRegistry: 'PROJECT_TABLES refs',
    reason: '删除静态 StoryArc 时必须与动态进度和交汇在同一事务内完成硬级联，避免孤儿投影。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'cultivation-codex-reference-lifecycle',
    target: 'codexEntries',
    entrypoints: [
      'src/lib/codex/references.ts',
      'src/lib/cultivation/lifecycle.ts',
      'src/lib/location/lifecycle.ts',
    ],
    policyRegistry: 'PROJECT_TABLES refs + cultivation DAG validator',
    reason: '删除词条、世界、修炼体系、境界节点或重要地点时，必须原子清理词条 JSON 引用及异兽体系/阶段/城池地点引用。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'cultivation-progress-lifecycle',
    target: 'cultivationProgress',
    entrypoints: [
      'src/lib/cultivation/progress.ts',
      'src/lib/cultivation/progress-lifecycle.ts',
    ],
    policyRegistry: 'ADOPTION_SCHEMAS + PROJECT_TABLES + cultivation DAG validator + canonical chapter sequence',
    reason: '修炼进度候选须经正文逐字证据、闭集 ID、DAG 路径和规范章序校验；角色、章节、体系与阶段删除需保留历史证据并降级软引用。',
    reviewAfter: '2027-01-01',
  },
  {
    id: 'workspace-root-lifecycle',
    target: 'projects',
    entrypoints: [
      'src/lib/export/registry-import.ts',
      'src/lib/memory/workspace-projection.ts',
      'src/lib/world-engine/world-package.ts',
      'src/lib/workspace/lifecycle.ts',
      'src/lib/workspace/ownership.ts',
      'src/lib/world-engine/releases.ts',
      'src/lib/workspace/works.ts',
      'src/lib/workspace/create-workspace.ts',
      'src/lib/world-engine/derivation.ts',
      'src/lib/world-engine/promotion.ts',
      'src/lib/adaptation/source-manifest.ts',
    ],
    policyRegistry: 'PROJECT_TABLES + workspace purpose + import trust + world lifecycle',
    reason: '项目根创建、当前格式导入恢复和世界/作品根级联属于受信生命周期；缺失身份直接拒绝，作者可编辑字段仍只能经 adopt()。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'world-root-lifecycle',
    target: 'worlds',
    entrypoints: [
      'src/lib/world-engine/world-package.ts',
      'src/lib/workspace/lifecycle.ts',
      'src/lib/workspace/ownership.ts',
      'src/lib/world-engine/releases.ts',
      'src/lib/workspace/create-workspace.ts',
      'src/lib/world-engine/derivation.ts',
      'src/lib/world-engine/promotion.ts',
    ],
    policyRegistry: 'PROJECT_TABLES refs + world package trust + world release lifecycle',
    reason: 'World 根创建、版本推进和引用级联是注册表约束的领域生命周期，不接受模型自由字段写回。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'work-root-lifecycle',
    target: 'works',
    entrypoints: [
      'src/lib/memory/workspace-projection.ts',
      'src/lib/workspace/lifecycle.ts',
      'src/lib/workspace/ownership.ts',
      'src/lib/workspace/works.ts',
      'src/lib/workspace/create-workspace.ts',
      'src/lib/world-engine/derivation.ts',
      'src/lib/adaptation/source-manifest.ts',
      'src/lib/adaptation/completion.ts',
    ],
    policyRegistry: 'PROJECT_TABLES refs + WorkspaceScope + stable work code + narrative lifecycle',
    reason: 'Work 根创建、稳定 code 补齐和级联是受信生命周期；删除最后一个独占叙事蓝图时还必须原子清空 activeNarrativeModuleId。标题等作者内容仍经 adopt()。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'adaptation-root-lifecycle',
    target: 'adaptationProjects',
    entrypoints: ['src/lib/adaptation/source-manifest.ts', 'src/lib/adaptation/completion.ts'],
    policyRegistry: 'PROJECT_TABLES + ADOPTION_SCHEMAS + adaptation state machine + source manifest CAS',
    reason: '改编创建、来源重同步、Brief/Plan 确认与阶段推进必须同步校验来源 manifest、目标 Work 和 revision；模型可编辑字段仍只作为候选进入正式确认服务。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'adaptation-source-manifest-lifecycle',
    target: 'adaptationSourceUnits',
    entrypoints: ['src/lib/adaptation/source-manifest.ts'],
    policyRegistry: 'PROJECT_TABLES + immutable source manifest policy + canonical chapter sequence',
    reason: '来源单元是创建或显式同步时原子追加的不可变证据，不是可由模型逐行采纳的内容表。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'screenplay-scene-lifecycle',
    target: 'screenplayScenes',
    entrypoints: ['src/lib/screenplay/service.ts', 'src/lib/screenplay/adoption.ts'],
    policyRegistry: 'PROJECT_TABLES + FIELD_REGISTRY + ADOPTION_SCHEMAS + screenplay block validator + adaptation freshness CAS',
    reason: '剧本场景的创建、排序、拆分、锁定和删除需要跨场景唯一约束、来源版本与块级引用校验；AI 批次仍须经同一 validator 原子采纳。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'comic-page-panel-lifecycle',
    target: 'comicPages',
    entrypoints: ['src/lib/comic/service.ts', 'src/lib/comic/adoption.ts'],
    policyRegistry: 'PROJECT_TABLES + FIELD_REGISTRY + ADOPTION_SCHEMAS + comic geometry/lettering validator + adaptation freshness CAS',
    reason: '漫画页格的父子临时映射、布局、重叠、来源版本、锁定和批次采纳必须在同一领域事务内完成。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'comic-panel-lifecycle',
    target: 'comicPanels',
    entrypoints: ['src/lib/comic/service.ts', 'src/lib/comic/adoption.ts', 'src/lib/comic/media-service.ts'],
    policyRegistry: 'PROJECT_TABLES + FIELD_REGISTRY + ADOPTION_SCHEMAS + comic panel validator',
    reason: '漫画格包含几何、连续性、排字和稳定媒资选择；普通字段采纳不能绕过父页布局与媒资一致性校验。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'comic-visual-subject-lifecycle',
    target: 'comicVisualSubjects',
    entrypoints: ['src/lib/comic/service.ts', 'src/lib/comic/media-service.ts'],
    policyRegistry: 'PROJECT_TABLES + FIELD_REGISTRY + ADOPTION_SCHEMAS + Work cast/source/asset stable-key validator',
    reason: '视觉条目删除与修改必须处理格连续性引用、所选设定图和角色绑定，不能由组件直接删表。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'comic-media-asset-lifecycle',
    target: 'comicMediaAssets',
    entrypoints: ['src/lib/comic/media-service.ts', 'src/lib/comic/service.ts'],
    policyRegistry: 'PROJECT_TABLES + media capability registry + hash/rights/provider receipt + stable-key reference checks',
    reason: '媒体候选不是普通文本字段；上传和 provider 结果必须先校验二进制、rights、owner 与请求证据，再原子提交并由作者另行选片。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'media-blob-object-lifecycle',
    target: 'mediaBlobObjects',
    entrypoints: [
      'src/lib/media/blob-store.ts',
      'src/lib/comic/media-service.ts',
      'src/lib/product-production/media-blob-store.ts',
      'src/lib/product-production/artifact-store.ts',
    ],
    policyRegistry: 'PROJECT_TABLES portable binary + PRODUCT_PRODUCTION_MEDIA_OBJECT_POLICY + SHA-256/MIME/dimension checks + lease/reference-aware GC',
    reason: '共享二进制对象必须 Work 隔离、内容寻址、hash 可验并可恢复；图片与通用上层产品媒资共用一个存储边界，删除须经过租约和注册引用复查。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'short-novel-outline-skeleton-lifecycle',
    target: 'outlineNodes',
    entrypoints: ['src/lib/workspace/create-workspace.ts'],
    policyRegistry: 'PROJECT_TABLES tree refs + WorkspaceScope + SHORT_NOVEL_WORKFLOW_OVERRIDES',
    reason: '作者创建短篇时须在 Workspace/World/Work 同一事务内建立单卷动态章节骨架；这不是模型候选采纳，后续大纲编辑仍走既有受治理入口。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'chapter-delete-lifecycle',
    target: 'chapters',
    entrypoints: [
      'src/lib/chapters/lifecycle.ts',
      'src/lib/workspace/create-workspace.ts',
    ],
    policyRegistry: 'PROJECT_TABLES refs + WorkspaceScope + chapter deletion impact policy + short skeleton policy',
    reason: '作者确认磁盘缺失后的级联删除与新建短篇的空章节骨架都要求领域事务；正文采纳或字段修改仍经 adopt()。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'chapter-emotion-delete-lifecycle',
    target: 'emotionBeatCards',
    entrypoints: ['src/lib/chapters/lifecycle.ts'],
    policyRegistry: 'PROJECT_TABLES chapter refs',
    reason: '章节删除时必须同步清除章节专属情感节拍，不能遗留孤儿记录。',
    reviewAfter: '2027-08-01',
  },
  {
    id: 'product-production-roots', target: 'productProductions',
    entrypoints: [
      'src/lib/product-production/commands.ts',
      'src/lib/product-production/artifact-store.ts',
      'src/lib/product-production/media-blob-store.ts',
      'src/lib/product-production/adoption.ts',
      'src/lib/product-production/scheduler.ts',
    ],
    policyRegistry: 'PRODUCT_PRODUCTION_COMMAND_POLICY + PRODUCT_PRODUCTION_ARTIFACT_POLICY + PROJECT_TABLES',
    reason: 'Production 状态、Brief 授权、幂等命令、Build/Artifact 和共享媒资必须维持 CAS、hash、scope、epoch 与引用完整性，不能由组件或 provider 直接散写。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'product-production-briefs', target: 'productProductionBriefs',
    entrypoints: ['src/lib/product-production/commands.ts', 'src/lib/product-production/adoption.ts'],
    policyRegistry: 'PRODUCT_PRODUCTION_COMMAND_POLICY + PROJECT_TABLES',
    reason: 'Brief revision 只能由命令 CAS 保存和授权，正式采用事务只能读取冻结 revision。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'product-production-commands', target: 'productProductionCommands',
    entrypoints: ['src/lib/product-production/commands.ts', 'src/lib/product-production/adoption.ts'],
    policyRegistry: 'PRODUCT_PRODUCTION_COMMAND_POLICY + PROJECT_TABLES',
    reason: '生产控制与发布必须先 claim 唯一 command receipt，再原子提交或记录失败。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'product-production-builds', target: 'productBuilds',
    entrypoints: [
      'src/lib/product-production/commands.ts',
      'src/lib/product-production/artifact-store.ts',
      'src/lib/product-production/adoption.ts',
      'src/lib/product-production/scheduler.ts',
      'src/lib/product-production/quality-receipts.ts',
    ],
    policyRegistry: 'PRODUCT_PRODUCTION_COMMAND_POLICY + PRODUCT_PRODUCTION_ARTIFACT_POLICY + PRODUCT_QUALITY_GATE_RECEIPT_V1 + PROJECT_TABLES',
    reason: 'Build 状态、epoch、hash 与发布指针必须通过登记的控制、Artifact 或整包采用事务变更；商业可发布状态只能由不可变性能与作者主路线回执的最新投影推进或降级。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'product-production-artifacts', target: 'productBuildArtifacts',
    entrypoints: [
      'src/lib/product-production/commands.ts',
      'src/lib/product-production/artifact-store.ts',
      'src/lib/product-production/adoption.ts',
      'src/lib/product-production/scheduler.ts',
    ],
    policyRegistry: 'PRODUCT_PRODUCTION_ARTIFACT_POLICY + PROJECT_TABLES',
    reason: '候选、验收、沿用与 orphan 状态必须校验 Build epoch、receipt、hash、scope 和唯一版本。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'product-production-release-adoption', target: 'productReleases',
    entrypoints: [
      'src/lib/product/releases.ts',
      'src/lib/product-production/adoption.ts',
      'src/lib/product-platform/distribution-bundle.ts',
    ],
    policyRegistry: 'PRODUCT_PRODUCTION_PACKAGE_ADOPTION_V1 + PRODUCT_DISTRIBUTION_BUNDLE_V2 + PROJECT_TABLES + product validators',
    reason: 'Production publish 只允许在单一事务中物化经 QA 的完整运行包；市场导入必须逐字验证分发包、媒资、世界来源、授权与来源回执，禁止分表发布或绕过产品 parser。',
    reviewAfter: '2027-08-21',
  },
  {
    id: 'ttrpg-rule-pack-library', target: 'ttrpgRulePacks',
    entrypoints: ['src/lib/ttrpg/rule-pack-library.ts'],
    policyRegistry: 'RULE_PACK_V1 parser + fixture verifier + immutable version identity + PROJECT_TABLES',
    reason: '规则包安装是人工或内置来源的版本化领域生命周期：写入前必须完成结构解析、行为夹具、许可声明与内容 hash 校验，并按 Work 与规则版本原子更新；模型候选字段仍统一走 adopt。',
    reviewAfter: '2027-08-21',
  },
])

/** C3: owner policy is derived from the same PROJECT_TABLES domainOwner metadata. */
export const ADOPTION_SCHEMAS: CollectionAdoptionSpec[] = ADOPTION_SCHEMAS_RAW.map(schema => ({
  ...schema,
  ownerFrom: schema.ownerFrom ?? (() => {
    const owner = REGISTRY_BY_NAME.get(schema.target)?.domainOwner?.defaultOwner
    return owner === 'world' || owner === 'work' ? owner : undefined
  })(),
}))

export const ADOPTION_BY_TARGET: ReadonlyMap<string, CollectionAdoptionSpec> = new Map(
  ADOPTION_SCHEMAS.map(s => [s.target, s] as const),
)
