import {expect,test,type Page} from '@playwright/test'
const fixture=async(page:Page)=>{
 await page.goto('./')
 return page.evaluate(async()=>{const imp=new Function('p','return import(p)');const {createWorkspace}=await imp('/storyforge/src/lib/workspace/create-workspace.ts');const {db}=await imp('/storyforge/src/lib/db/schema.ts');const a=await createWorkspace({name:'潮水来信',description:'独立创作的第一部作品',genres:[],status:'drafting',targetWordCount:10000},{kind:'novel',novelProfile:'long',importedNovelText:'# 第一章 铜铃\n\n只有这部作品包含 HOME_UNIQUE_728 的正文。'});const b=await createWorkspace({name:'独立的世界',description:'不属于小说列表',genres:[],status:'drafting',targetWordCount:10000},{purpose:'world-engine',kind:'novel',novelProfile:'long'});const chapters=await db.chapters.where('projectId').equals(a.project.id).toArray();return {projectId:a.project.id,workId:a.work.id,chapter:chapters[0].outlineNodeId,worldProjectId:b.project.id}})
}
test('home starts honestly empty and each global page remains browsable without creating data',async({page})=>{
 for(const route of ['', 'home/library','home/detail','home/cover','home/results','home/tasks','home/search','home/settings','home/data','home/products']){await page.goto('./'+route);await expect(page.getByTestId('home-page')).toBeVisible();await expect(page.getByText('雾港纪事',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:/全部页面/})).toHaveCount(0)}
 const counts=await page.evaluate(async()=>{const imp=new Function('p','return import(p)');const {db}=await imp('/storyforge/src/lib/db/schema.ts');return [await db.projects.count(),await db.works.count()]});expect(counts).toEqual([0,0]);await page.goto('./?tab=home');await expect(page.getByTestId('home-page')).toBeVisible();await page.screenshot({path:'/tmp/home-integrated-empty.png'})
})
test('home creates through the product page and resumes the exact real Work and chapter after refresh',async({page})=>{
 const ids=await fixture(page);await page.goto(`./workspace/${ids.projectId}?module=chapters-list&chapter=${ids.chapter}`);await expect(page.locator('.tiptap-editor')).toContainText('HOME_UNIQUE_728');await page.getByRole('button',{name:'返回首页',exact:true}).click();await expect(page.getByTestId('home-page')).toBeVisible();await expect(page.locator('.home-main')).toHaveCSS('overflow-y','auto');const mistHarbor=page.locator('.home-builtin').filter({has:page.getByRole('heading',{name:'雾港：失潮钟声',exact:true})});await expect(mistHarbor).toHaveCSS('background-image',/mist-bg-harbor/);await expect(page.locator('.home-builtin-openworld')).toBeVisible();await expect(page.getByRole('heading',{name:'潮水来信',exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'继续上次创作',exact:true}).click();await expect(page).toHaveURL(new RegExp(`workspace/${ids.projectId}\\?module=chapters-list&chapter=${ids.chapter}`));await expect(page.locator('.tiptap-editor')).toContainText('HOME_UNIQUE_728');
 await page.goto('./home/products');await page.getByRole('button',{name:/^长篇/}).click();await page.getByRole('button',{name:'新建长篇',exact:true}).click();await page.getByLabel('新长篇名称').fill('通过首页建立的新长篇');await page.getByRole('button',{name:'创建并进入工作台',exact:true}).click();await expect(page).toHaveURL(/workspace\/\d+/);await page.goto('./home/library');await expect(page.getByRole('heading',{name:'通过首页建立的新长篇',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'独立的世界',exact:true})).toHaveCount(0);await page.screenshot({path:'/tmp/home-integrated-library.png'})
})
test('home search returns real scoped prose and no results for a missing query',async({page})=>{
 const ids=await fixture(page);await page.goto('./home/search');await page.getByRole('textbox',{name:'搜索内容',exact:true}).fill('HOME_UNIQUE_728');await page.getByRole('main').getByRole('button',{name:'搜索',exact:true}).click();await expect(page.locator('.home-search-hit')).toHaveCount(1);await expect(page.locator('.home-search-hit')).toContainText('HOME_UNIQUE_728');await page.getByRole('button',{name:'查看内容',exact:true}).click();await expect(page).toHaveURL(new RegExp(`workspace/${ids.projectId}.*chapter=${ids.chapter}`));await expect(page.locator('.tiptap-editor')).toContainText('HOME_UNIQUE_728');await page.goto('./home/search');await page.getByRole('textbox',{name:'搜索内容',exact:true}).fill('NO_MATCH_932');await page.getByRole('main').getByRole('button',{name:'搜索',exact:true}).click();await expect(page.getByText('没有找到匹配内容，试试其他关键词或范围。')).toBeVisible();await expect(page.locator('.home-search-hit')).toHaveCount(0)
})
test('home settings use real shared configuration and preserve it after refresh',async({page})=>{
 await page.route('**/models',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:[{id:'home-local-model'}]})}));await page.goto('./home/settings');await page.locator('label:has-text("提供商") + select').selectOption('ollama');const base=page.locator('label:has-text("Base URL") + input');await base.fill('http://localhost:1234/v1/models');await page.getByRole('button',{name:'刷新模型',exact:true}).click();await page.getByLabel('服务返回的模型列表').selectOption('home-local-model');await page.reload();await expect(page.locator('input[placeholder="手动输入模型名"]')).toHaveValue('home-local-model');await expect(base).toHaveValue('http://localhost:1234/v1');await page.goto('./settings');await expect(page).toHaveURL(/home\/settings/);await expect(page.locator('input[placeholder="手动输入模型名"]')).toHaveValue('home-local-model')
})
test('home backup exports and imports an independent copy; cover belongs only to the selected Work',async({page})=>{
 const ids=await fixture(page);await page.goto(`./home/cover?work=${ids.workId}`);await page.getByLabel('上传封面').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=120;canvas.height=180;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#286c60';ctx.fillRect(0,0,120,180);return canvas.toDataURL('image/png').split(',')[1]}),'base64')});await expect(page.locator('img[alt="潮水来信的封面预览"]')).toBeVisible();await page.getByRole('button',{name:'保存封面',exact:true}).click();await expect(page.getByRole('status')).toContainText('封面已保存');await page.reload();await expect(page.locator('img[alt="潮水来信的封面预览"]')).toBeVisible();await page.goto(`./home/data?project=${ids.projectId}`);const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 JSON',exact:true}).click();const file=await(await download).path();await page.getByLabel('导入 JSON 备份',{exact:true}).setInputFiles(file!);await page.getByRole('dialog').getByRole('button',{name:'确认导入',exact:true}).click();await expect(page).not.toHaveURL(new RegExp(`project=${ids.projectId}$`));await expect(page.getByRole('heading',{name:'数据管理',exact:true})).toBeVisible();const counts=await page.evaluate(async()=>{const imp=new Function('p','return import(p)');const {db}=await imp('/storyforge/src/lib/db/schema.ts');return {works:await db.works.filter(w=>w.title==='潮水来信').count(),covers:await db.works.filter(w=>!!w.coverImage).count()}});expect(counts).toEqual({works:2,covers:2})
})
test('narrow home retains every navigation entry and the actual settings fields',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('./');await expect(page.getByRole('button',{name:'页面目录',exact:true})).toBeVisible();await page.getByRole('button',{name:'页面目录',exact:true}).click();await page.getByRole('navigation',{name:'首页导航'}).getByRole('button',{name:'设置',exact:true}).click();await expect(page.locator('label:has-text("提供商") + select')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'/tmp/home-integrated-mobile-settings.png'});await page.goto('./');await expect(page.getByRole('heading',{name:/天地为炉，\s*万象成故事。/})).toBeVisible();await page.screenshot({path:'/tmp/home-integrated-mobile.png'})
})
test('home lists persisted tasks and opens the correct outline; invalid task stays explicit',async({page})=>{
 const ids=await fixture(page)
 const runId=await page.evaluate(async({projectId,workId})=>{
  const imp=new Function('p','return import(p)');const {db}=await imp('/storyforge/src/lib/db/schema.ts');const {createAgentRunV1,appendAgentRunEventV1}=await imp('/storyforge/src/lib/agent/run/event-store.ts');const work=await db.works.get(workId);const scope={projectId,workId,worldId:work.worldId};
  const run=await createAgentRunV1({scope,worldGroupId:null,contract:{version:1,runtimeBindingHash:'a'.repeat(64),objective:'待作者检查的章纲任务',workflowKind:'long-running-resumable',scope:{projectId,worldGroupId:null},permissions:{contextSourceKeys:['worldview','storyCore'],writeTargets:[{table:'outlineNodes',fields:['summary'],mode:'candidate-only'}]},budget:{maxModelCalls:3,maxToolCalls:4,maxInputTokens:8000,maxOutputTokens:2000,maxAttemptsPerStep:2},acceptance:[{id:'outline.output',kind:'output-present',required:true}],verificationPlan:[{id:'outline.terminal',kind:'terminal',verifier:'terminal-v1',criterionIds:['outline.output']}],failurePolicy:{onProtocolError:'fail',onVerificationFailure:'fail',onStaleInput:'pause-for-author'}}});
  await appendAgentRunEventV1({scope,runId:run.run.id,type:'step.scheduled',payload:{stepId:'outline.generate'}});await appendAgentRunEventV1({scope,runId:run.run.id,type:'step.started',payload:{stepId:'outline.generate',attempt:1}});await appendAgentRunEventV1({scope,runId:run.run.id,type:'run.paused',payload:{reason:'作者暂停检查',recoverable:true}});return run.run.id
 },ids)
 await page.goto('./');await expect(page.getByRole('heading',{name:'待作者检查的章纲任务',exact:true})).toBeVisible();await page.getByRole('button',{name:'查看任务',exact:true}).click();await expect(page).toHaveURL(new RegExp(`home/tasks\\?run=${runId}$`));await expect(page.getByRole('region',{name:'任务详情'})).toContainText('已暂停');await page.getByRole('button',{name:'打开所属作品',exact:true}).click();await expect(page).toHaveURL(new RegExp(`workspace/${ids.projectId}\\?module=outline$`));await page.goto('./home/tasks?run=999999');await expect(page.getByRole('alert')).toContainText('这条任务已被移除')
})
test('home rejects an invalid backup without creating or replacing local works',async({page})=>{
 await fixture(page);await page.goto('./home/data');await page.getByLabel('导入 JSON 备份',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"projects":[]}')});await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await page.goto('./home/library');await expect(page.getByRole('heading',{name:'潮水来信',exact:true})).toBeVisible();await expect(page.locator('.home-work-card')).toHaveCount(1)
})
