import { expect, test } from '@playwright/test'
import { createLongform } from './helpers/product-entry'

test('theme selection persists, colors shared surfaces and can return to the green default', async ({ page }) => {
  await page.goto('./home/settings')
  const inkwash = page.getByRole('button', { name: '水墨远山', exact: true })
  await inkwash.focus()
  await page.keyboard.press('Enter')
  await expect(inkwash).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'inkwash')
  await expect(inkwash).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.longform-app')).toHaveCSS('background-image', /inkwash.*webp/)
  await expect(page.locator('.lf-top')).toHaveCSS('color', 'rgb(53, 61, 56)')
  await page.goto('./adventure/vision')
  await expect(page.locator('.longform-app')).toHaveCSS('background-image', /inkwash.*webp/)
  await expect(page.locator('.lf-paper').first()).toHaveCSS('background-color', 'rgba(250, 247, 237, 0.96)')
  await page.goto('./home/settings')
  await page.getByRole('button', { name: '青绿山水', exact: true }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'storyforge')
  await expect(page.locator('.longform-app')).toHaveCSS('background-image', /shell.*jpg/)
  await expect(page.locator('.lf-top')).toHaveCSS('color', 'rgb(235, 239, 225)')
})

test('switching skins preserves saved prose and portal dialogs use the selected paper', async ({ page }) => {
  await createLongform(page, '水墨主题验证')
  await page.getByRole('navigation', { name: '长篇工作台二级导航' }).getByRole('button', { name: '大纲与章纲', exact: true }).click()
  await page.getByRole('button', { name: '添加卷', exact: true }).click()
  await page.getByRole('button', { name: '添加章节', exact: true }).click()
  await page.getByTitle('编辑章节', { exact: true }).click()
  const editor = page.locator('.tiptap-editor')
  const prose = '雨过远山，渡口的小船仍泊在苇花深处。'
  await editor.fill(prose)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('button', { name: '已保存', exact: true })).toBeVisible()
  const chapterUrl = page.url()
  await page.goto('./home/settings')
  await page.getByRole('button', { name: '水墨远山', exact: true }).click()
  await page.goto(chapterUrl)
  await expect(editor).toContainText(prose)
  await expect(editor).toHaveCSS('color', 'rgb(51, 61, 56)')
  await expect(page.locator('.sf-manuscript-editor > div:last-child')).toHaveCSS('background-color', 'rgb(250, 247, 237)')
  await page.reload()
  await expect(editor).toContainText(prose)
  await page.goto('./long')
  await page.getByRole('button', { name: '重命名', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCSS('background-color', 'rgb(250, 247, 237)')
  await page.getByRole('dialog').getByRole('textbox').fill('远山来信')
  await page.getByRole('button', { name: '保存名称', exact: true }).click()
  await expect(page.getByRole('heading', { name: '远山来信', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '远山来信', exact: true })).toBeVisible()
  await page.goto(chapterUrl)
  await expect(editor).toContainText(prose)
})

test('inkwash navigation stays readable without horizontal overflow on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./home/settings')
  await page.getByRole('button', { name: '水墨远山', exact: true }).click()
  await page.getByRole('button', { name: '页面目录', exact: true }).click()
  await expect(page.locator('.lf-sidebar')).toHaveCSS('background-color', 'rgb(237, 231, 217)')
  await expect(page.locator('.lf-sidebar')).toHaveCSS('color', 'rgb(53, 61, 56)')
  await page.getByRole('navigation', { name: '首页导航' }).getByRole('button', { name: '今天', exact: true }).click()
  await expect(page.locator('.home-hero')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
