import { expect, test } from '@playwright/test'
import { openProductTab, seedCurrentTtrpgProduct } from './helpers/current-products'
import { installKpRehearsal, reachHumanTurn } from './helpers/ttrpg-kp-rehearsal'

test('AI KP 主桌面：开团、调查、私密询问、失败恢复与刷新', async ({ page }) => {
  const transport = await installKpRehearsal(page)
  const fixture = await seedCurrentTtrpgProduct(page, { title: '雾港 · 主桌面排练', gmMode: 'ai', playerController: 'human' })
  await page.reload()
  await openProductTab(page, 'ttrpg')
  const table = page.getByTestId('ttrpg-play-table')
  await expect(table.getByText('选择你要扮演的人')).toBeVisible()
  await table.getByRole('checkbox').check()
  await table.getByRole('button', { name: '与 AI KP 开始冒险', exact: true }).click()
  await reachHumanTurn(page)
  await table.getByLabel('行动方式').selectOption('investigate')
  await table.getByLabel(/现在是你的回合/).fill('我沿着石阶检查灯油留下的痕迹。')
  const priorActions = await table.getByRole('log').locator('.sf-ttrpg-action').count()
  await table.getByRole('button', { name: '先询问 KP', exact: true }).click()
  await expect(table.getByLabel('KP 的判定建议')).toContainText('先保护自己的线索')
  await expect(table.getByRole('log').locator('.sf-ttrpg-action')).toHaveCount(priorActions)
  await expect(table.getByRole('log')).not.toContainText('先保护自己的线索')
  await table.getByRole('button', { name: '采用这个行动方式', exact: true }).click()
  await expect(table.getByLabel('行动方式')).toHaveValue('investigate')
  transport.failOnce()
  await table.getByRole('button', { name: '采取行动', exact: true }).click()
  await expect(table.getByRole('alert')).toContainText('rehearsal unauthorized')
  const failedCalls = transport.calls()
  await page.waitForTimeout(300)
  expect(transport.calls()).toBe(failedCalls)
  await table.getByRole('button', { name: '从当前进度继续主持', exact: true }).click()
  await reachHumanTurn(page)
  await expect(table.getByRole('log')).toContainText('潮声从石阶下传来')
  await table.getByRole('button', { name: /我的秘密/ }).click()
  await table.getByLabel('悄悄询问 KP').fill('怎样保护我的私人目标？')
  await table.getByRole('button', { name: '只给我的指引', exact: true }).click()
  await expect(table.locator('.sf-ttrpg-private')).toContainText('先保护自己的线索')
  await expect(table.getByRole('log')).not.toContainText('先保护自己的线索')
  await page.screenshot({ path: 'test-results/ttrpg-ai-kp-desktop.png', fullPage: true })
  await page.reload()
  await openProductTab(page, 'ttrpg')
  await expect(table.getByRole('log')).toContainText('潮声从石阶下传来')
  await expect(table.locator('.sf-ttrpg-whisper')).toHaveCount(0)
  await table.getByRole('button', { name: /我的秘密/ }).click()
  await expect(table.locator('.sf-ttrpg-private')).toContainText('先保护自己的线索')
  await page.goto(`./play/session/${fixture.sessionId}`)
  await expect(table.getByRole('log')).toContainText('潮声从石阶下传来')
  await page.screenshot({ path: 'test-results/ttrpg-ai-kp-immersive.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(table).toBeVisible()
  await page.screenshot({ path: 'test-results/ttrpg-ai-kp-mobile.png', fullPage: true })
  expect(fixture.sessionId).toBeGreaterThan(0)
})
