import { expect, test } from '@playwright/test'
import { seedCurrentTtrpgProduct } from './helpers/current-products'
import { installKpRehearsal, reachHumanTurn } from './helpers/ttrpg-kp-rehearsal'

test('目录不可用时仍能读取本地存档，另一标签新增存档后列表自动更新', async ({ page, context }) => {
  await installKpRehearsal(page)
  const first = await seedCurrentTtrpgProduct(page, { title: '离线目录中的冒险', gmMode: 'ai', playerController: 'human' })
  let unavailable = true
  await page.route('**/games/catalog.json', route => unavailable ? route.fulfill({ status: 503, body: 'unavailable' }) : route.continue())
  await page.goto('./play')
  await expect(page.getByRole('alert')).toContainText('已有存档仍可在下方打开')
  const saves = page.getByRole('region', { name: '本地冒险存档' })
  await expect(saves.getByRole('link', { name: /离线目录中的冒险/ })).toBeVisible()
  const other = await context.newPage()
  await seedCurrentTtrpgProduct(other, { title: '另一窗口的新冒险', gmMode: 'ai', playerController: 'human' })
  await expect(saves.getByRole('link', { name: /另一窗口的新冒险/ })).toBeVisible()
  await other.close()
  unavailable = false
  await page.getByRole('button', { name: '重新加载游戏目录' }).click()
  await expect(page.getByRole('heading', { name: '雾港：最后一盏灯' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await saves.getByRole('link', { name: /离线目录中的冒险/ }).click()
  await expect(page).toHaveURL(new RegExp(`/play/session/${first.sessionId}$`))
  await expect(page.getByTestId('ttrpg-play-table')).toBeVisible()
})

test('社区真实游戏包：多人刷新和交接遮屏，检查点另建冒险，手机桌面可用', async ({ page }) => {
  test.setTimeout(120_000)
  await installKpRehearsal(page)
  await page.goto('./')
  await page.getByRole('button', { name: '体验原创跑团', exact: true }).click()
  await expect(page).toHaveURL(/\/storyforge\/play$/)
  await page.getByRole('button', { name: '开始一场新冒险' }).click()
  const table = page.getByTestId('ttrpg-play-table')
  await table.getByRole('button', { name: /本地多人轮流玩/ }).click()
  await table.getByRole('checkbox').check()
  await table.getByRole('button', { name: '与 AI KP 开始冒险', exact: true }).click()
  await expect(table.locator('.sf-ttrpg-progress')).toHaveCount(0, { timeout: 30_000 })
  const gate = table.getByRole('region', { name: '交接桌面' })
  if (await gate.isVisible()) await gate.getByRole('button', { name: /继续冒险/ }).click()
  await table.getByRole('button', { name: /我的秘密/ }).click()
  const oldSecret = await table.locator('.sf-ttrpg-private>div>p').first().innerText()
  expect(oldSecret.length).toBeGreaterThan(10)
  await table.getByRole('button', { name: '存档', exact: true }).click()
  await expect(table.locator('.sf-ttrpg-progress')).toHaveCount(0)
  await table.getByRole('button', { name: '遮住桌面', exact: true }).click()
  await expect(gate).toBeVisible()
  await expect(table).not.toContainText(oldSecret)
  await expect(table.getByRole('log')).toHaveCount(0)
  await expect(table.locator('.sf-ttrpg-notebook')).toHaveCount(0)
  await page.reload()
  await expect(gate).toBeVisible()
  await expect(table.getByRole('log')).toHaveCount(0)
  await gate.getByRole('button', { name: /继续冒险/ }).click()
  await expect(table).not.toContainText(oldSecret)
  await table.getByRole('button', { name: /我的秘密/ }).click()
  await expect(table.locator('.sf-ttrpg-private')).toContainText(oldSecret)
  // Give the next human their reaction/turn through the real runtime commands.
  for (let step = 0; step < 10 && !await gate.isVisible(); step++) {
    const observe = table.getByRole('button', { name: '暂时观察，让故事继续', exact: true })
    if (await observe.isVisible()) await observe.click()
    else if (await table.getByLabel(/现在是你的回合/).isVisible()) {
      await table.getByLabel('行动方式').selectOption('investigate')
      await table.getByLabel(/现在是你的回合/).fill('我查看码头上留下的痕迹，试着找到可以核实的记录。')
      await table.getByRole('button', { name: '采取行动', exact: true }).click()
    } else await table.getByRole('button', { name: '继续主持', exact: true }).click()
    await expect(table.locator('.sf-ttrpg-progress')).toHaveCount(0, { timeout: 30_000 })
  }
  await expect(gate).toBeVisible()
  await expect(table).not.toContainText(oldSecret)
  await gate.getByRole('button', { name: /继续冒险/ }).click()
  await table.getByRole('button', { name: /我的秘密/ }).click()
  await expect(table.locator('.sf-ttrpg-private')).not.toContainText(oldSecret)
  const currentUrl = page.url()
  await page.locator('.sf-community-checkpoints summary').click()
  await page.locator('.sf-community-checkpoints').getByRole('button', { name: /手动存档/ }).click()
  await expect(page).not.toHaveURL(currentUrl)
  await expect(gate).toBeVisible()
  await expect(table.getByRole('log')).toHaveCount(0)
  await gate.getByRole('button', { name: /继续冒险/ }).click()
  await expect(table.getByRole('heading', { level: 2 })).toHaveText('雾港：最后一盏灯')
  await expect(table.locator('.sf-ttrpg-save-label')).toContainText('手动存档')
  await page.screenshot({ path: 'test-results/ttrpg-iteration-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(table.getByRole('button', { name: '遮住桌面', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await table.getByRole('button', { name: '遮住桌面', exact: true }).click()
  await expect(gate).toBeVisible()
  await page.screenshot({ path: 'test-results/ttrpg-iteration-mobile-gate.png', fullPage: true })
})


test('单人选择非默认角色后，开团与刷新都保持本人的控制权和私密资料', async ({ page }) => {
  await installKpRehearsal(page)
  await page.goto('./play')
  await page.getByRole('button', { name: '开始一场新冒险' }).click()
  const table = page.getByTestId('ttrpg-play-table')
  await table.getByRole('button', { name: /乔屿.*选择角色/ }).click()
  await table.getByRole('checkbox').check()
  await table.getByRole('button', { name: '与 AI KP 开始冒险', exact: true }).click()
  await reachHumanTurn(page)
  await expect(table.getByLabel(/现在是你的回合/)).toHaveAccessibleName('现在是你的回合，乔屿。')
  await table.getByRole('button', { name: /我的秘密/ }).click()
  const secret = await table.locator('.sf-ttrpg-private>div>p').first().innerText()
  await page.reload()
  await expect(table.getByRole('region', { name: '交接桌面' })).toHaveCount(0)
  await expect(table.getByLabel(/现在是你的回合/)).toHaveAccessibleName('现在是你的回合，乔屿。')
  await expect(table).not.toContainText(secret)
  await table.getByRole('button', { name: /我的秘密/ }).click()
  await expect(table.locator('.sf-ttrpg-private')).toContainText(secret)
})
