import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, Play, RefreshCw, Sparkles, X } from 'lucide-react'
import type { AdaptationProject, AdaptationSourceUnit, ComicPage, ComicPanel, ComicReviewIssueV1, WorkspaceScope } from '../../lib/types'
import { listAdaptationAnalysisV1 } from '../../lib/adaptation/analysis'
import { getAIConfigRequiredMessage, isAIConfigReady } from '../../lib/ai/config-readiness'
import {
  adoptComicProfessionalCandidateV1,
  generateComicProfessionalCandidateV1,
  readPendingComicProfessionalCandidateV1,
  rejectComicProfessionalCandidateV1,
  type ComicProfessionalPayloadV1,
  type ComicProfessionalStageV1,
} from '../../lib/comic/durable-production'
import { listComicProductionV1, startComicProductionV1, updateComicReviewIssueStatusV1 } from '../../lib/comic/production'
import { useAIConfigStore } from '../../stores/ai-config'

interface Props { scope: WorkspaceScope; adaptation: AdaptationProject; sourceUnits: AdaptationSourceUnit[]; pages: ComicPage[]; panels: ComicPanel[]; subjectCount: number; onChanged: () => Promise<void> }
const LABELS: Record<ComicProfessionalStageV1, string> = {
  'source-analysis': '1 来源事实', 'causal-graph': '2 因果图', 'adaptation-brief': '3 改编 Brief', 'decision-pass': '4 删改决定',
  'script-adaptation': '5 漫画脚本', 'page-rhythm': '6 分页节奏', 'panel-plan': '7 页格分镜', 'visual-bible': '8 视觉圣经',
  'image-request': '9 图片请求', 'visual-continuity-review': '10 视觉监修', 'targeted-repair': '11 定点修复', 'page-review': '12 页级审校',
}
function payloadKeys(payload: unknown): string[] { return Array.isArray(payload) ? payload.flatMap(item => item && typeof item === 'object' && typeof item.stableKey === 'string' ? [item.stableKey] : []) : [] }

export default function ComicPipelinePanel({ scope, adaptation, sourceUnits, pages, panels, subjectCount, onChanged }: Props) {
  const [counts, setCounts] = useState({ facts: 0, edges: 0, decisions: 0, beats: 0, plans: 0, issues: 0 })
  const [covered, setCovered] = useState<string[]>([]); const [issues, setIssues] = useState<ComicReviewIssueV1[]>([])
  const [sourceKey, setSourceKey] = useState(''); const [pageKey, setPageKey] = useState(''); const [panelKey, setPanelKey] = useState('')
  const [candidate, setCandidate] = useState<{ runId: number; stage: ComicProfessionalStageV1; text: string } | null>(null); const [accepted, setAccepted] = useState<Set<string>>(new Set()); const [authorVisualInspectionConfirmed, setAuthorVisualInspectionConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const aiConfig = useAIConfigStore(state => state.config)
  const reload = useCallback(async () => { const [analysis, production] = await Promise.all([listAdaptationAnalysisV1({ scope, adaptationProjectId: adaptation.id!, manifestVersion: adaptation.activeSourceManifestVersion }), listComicProductionV1(scope)]); const facts = analysis.facts.filter(row => row.authorStatus === 'confirmed'); setCounts({ facts: facts.length, edges: analysis.edges.filter(row => row.authorStatus === 'confirmed').length, decisions: analysis.decisions.filter(row => row.authorStatus === 'confirmed').length, beats: production.scriptBeats.length, plans: production.pagePlans.length, issues: production.reviewIssues.filter(row => row.status === 'open').length }); setCovered([...new Set(facts.flatMap(row => row.sourceUnitKeys))]); setIssues(production.reviewIssues) }, [adaptation.activeSourceManifestVersion, adaptation.id, scope])
  useEffect(() => { void reload().catch(cause => setError(cause instanceof Error ? cause.message : '读取漫画专业流程失败')) }, [reload])
  useEffect(() => { const usable = sourceUnits.filter(row => row.sourceKind !== 'work'); setSourceKey(current => current && usable.some(row => row.sourceUnitKey === current) ? current : usable.find(row => !covered.includes(row.sourceUnitKey))?.sourceUnitKey ?? usable[0]?.sourceUnitKey ?? '') }, [covered, sourceUnits])
  useEffect(() => { setPageKey(current => current && pages.some(row => row.stableKey === current) ? current : pages[0]?.stableKey ?? '') }, [pages])
  useEffect(() => { const page = pages.find(row => row.stableKey === pageKey); const rows = panels.filter(row => row.pageId === page?.id); setPanelKey(current => current && rows.some(row => row.stableKey === current) ? current : rows[0]?.stableKey ?? '') }, [pageKey, pages, panels])
  useEffect(() => { let cancelled = false; void readPendingComicProfessionalCandidateV1(scope).then(pending => { if (!pending || cancelled) return; setCandidate({ runId: pending.snapshot.run.id, stage: pending.candidate.stage, text: JSON.stringify(pending.candidate.payload, null, 2) }); setAccepted(new Set(payloadKeys(pending.candidate.payload))); setAuthorVisualInspectionConfirmed(false) }).catch(() => undefined); return () => { cancelled = true } }, [scope])
  const openIssues = useMemo(() => issues.filter(row => row.status === 'open' && (!row.panelKey || row.panelKey === panelKey) && row.pageKey === pageKey), [issues, pageKey, panelKey])
  const candidateRows = useMemo(() => { if (!candidate) return []; try { const parsed = JSON.parse(candidate.text); return Array.isArray(parsed) ? parsed : [] } catch { return [] } }, [candidate])
  const run = async (stage: ComicProfessionalStageV1) => { if (busy || candidate) return; if (!isAIConfigReady(aiConfig)) return setError(getAIConfigRequiredMessage(aiConfig)); setBusy(true); setError(''); try { const generated = await generateComicProfessionalCandidateV1({ scope, adaptationProjectId: adaptation.id!, stage, aiConfig, sourceUnitKeys: stage === 'source-analysis' ? [sourceKey] : undefined, targetPageKeys: ['visual-continuity-review', 'page-review'].includes(stage) ? [pageKey] : undefined, targetPanelKeys: ['image-request', 'targeted-repair'].includes(stage) ? [panelKey] : undefined, targetIssueKeys: stage === 'targeted-repair' ? openIssues.map(row => row.stableKey) : undefined }); setCandidate({ runId: generated.snapshot.run.id, stage, text: JSON.stringify(generated.candidate.payload, null, 2) }); setAccepted(new Set(payloadKeys(generated.candidate.payload))); setAuthorVisualInspectionConfirmed(false) } catch (cause) { setError(cause instanceof Error ? cause.message : '专业阶段生成失败') } finally { setBusy(false) } }
  const accept = async () => { if (!candidate || busy) return; setBusy(true); setError(''); try { const parsed = JSON.parse(candidate.text) as ComicProfessionalPayloadV1; const authorPayload = Array.isArray(parsed) ? parsed.filter(item => item && typeof item === 'object' && accepted.has((item as { stableKey: string }).stableKey)) : parsed; await adoptComicProfessionalCandidateV1({ scope, runId: candidate.runId, authorPayload: authorPayload as ComicProfessionalPayloadV1, authorVisualInspectionConfirmed }); setCandidate(null); setAccepted(new Set()); setAuthorVisualInspectionConfirmed(false); await reload(); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : '采纳候选失败') } finally { setBusy(false) } }
  const reject = async () => { if (!candidate || busy) return; setBusy(true); setError(''); try { await rejectComicProfessionalCandidateV1(scope, candidate.runId); setCandidate(null); setAccepted(new Set()); setAuthorVisualInspectionConfirmed(false) } catch (cause) { setError(cause instanceof Error ? cause.message : '放弃候选失败') } finally { setBusy(false) } }
  const readyBrief = adaptation.briefSourceManifestVersion === adaptation.activeSourceManifestVersion
  const buttons: Array<{ stage: ComicProfessionalStageV1; ready: boolean; detail: string }> = [
    { stage: 'source-analysis', ready: Boolean(sourceKey), detail: `${covered.length}/${sourceUnits.filter(row => row.sourceKind !== 'work').length} 单元 · ${counts.facts} 事实` }, { stage: 'causal-graph', ready: counts.facts > 0, detail: `${counts.edges} 因果边` }, { stage: 'adaptation-brief', ready: counts.edges > 0, detail: readyBrief ? '已确认' : '待确认' }, { stage: 'decision-pass', ready: readyBrief, detail: `${counts.decisions} 决定` },
    { stage: 'script-adaptation', ready: counts.decisions > 0, detail: `${counts.beats} 节拍` }, { stage: 'page-rhythm', ready: counts.beats > 0, detail: `${counts.plans}/${adaptation.targetSpec.format === 'page-comic' ? adaptation.targetSpec.chapterCount * adaptation.targetSpec.targetPagesPerChapter : 0} 页` }, { stage: 'panel-plan', ready: counts.plans > 0, detail: `${pages.length} 页 · ${panels.length} 格` }, { stage: 'visual-bible', ready: counts.plans > 0 && pages.length > 0, detail: `${subjectCount} Subject` },
    { stage: 'image-request', ready: Boolean(panelKey && subjectCount), detail: panelKey || '选择目标格' }, { stage: 'visual-continuity-review', ready: Boolean(pageKey && subjectCount), detail: '机器证据 + 作者验图' }, { stage: 'targeted-repair', ready: Boolean(panelKey && openIssues.length), detail: `${openIssues.length} 个目标问题` }, { stage: 'page-review', ready: Boolean(pageKey), detail: '叙事/顺序/排字' },
  ]
  return <section className="comic-pipeline"><header><div><span>PROFESSIONAL COMIC PIPELINE</span><h3>十二步小说转漫画</h3></div><strong>manifest v{adaptation.activeSourceManifestVersion}</strong></header><p>每个岗位只生成自己的候选；协议错误最多自动修复一次并记入运行事件，作者确认后才写正式表。成图、排字、审查和发布各自保留证据。</p>
    <div className="comic-pipeline-targets"><label>来源分析单元<select value={sourceKey} onChange={event => setSourceKey(event.target.value)}>{sourceUnits.filter(row => row.sourceKind !== 'work').map(row => <option key={row.sourceUnitKey} value={row.sourceUnitKey}>{covered.includes(row.sourceUnitKey) ? '✓ ' : ''}{row.label} · {row.wordCount} 字</option>)}</select></label><label>目标页<select value={pageKey} onChange={event => setPageKey(event.target.value)}>{pages.map(row => <option key={row.stableKey} value={row.stableKey}>{row.stableKey} · {row.summary}</option>)}</select></label><label>目标格<select value={panelKey} onChange={event => setPanelKey(event.target.value)}>{panels.filter(row => row.pageId === pages.find(page => page.stableKey === pageKey)?.id).map(row => <option key={row.stableKey} value={row.stableKey}>{row.stableKey} · {row.moment ?? row.action}</option>)}</select></label>{pages.length > 0 && subjectCount > 0 && !['producing', 'review', 'complete'].includes(adaptation.status) && <button className="primary" onClick={() => void (async () => { setBusy(true); setError(''); try { await startComicProductionV1({ scope, expectedAdaptationRevision: adaptation.revision }); await onChanged() } catch (cause) { setError(cause instanceof Error ? cause.message : '进入生产失败') } finally { setBusy(false) } })()} disabled={busy}><Play />进入图片生产</button>}</div>
    <div className="comic-pipeline-steps">{buttons.map(item => <button key={item.stage} onClick={() => void run(item.stage)} disabled={busy || !!candidate || !item.ready || adaptation.status === 'complete'}><Sparkles /><span><strong>{LABELS[item.stage]}</strong><small>{item.detail}</small></span></button>)}</div>
    {candidate && <div className="comic-professional-candidate"><header><strong>{LABELS[candidate.stage]}候选 · 尚未写入</strong><span>可编辑后确认</span></header>{candidateRows.length > 0 && <div className="comic-candidate-items">{candidateRows.map((item: any, index) => <label key={item.stableKey ?? index}><input type="checkbox" checked={accepted.has(item.stableKey)} onChange={event => setAccepted(current => { const next = new Set(current); if (event.target.checked) next.add(item.stableKey); else next.delete(item.stableKey); return next })} /><span><strong>{item.stableKey}</strong><small>{item.statement ?? item.rationale ?? item.visualAction ?? item.goal ?? item.moment ?? item.problem ?? ''}</small></span></label>)}</div>}<textarea value={candidate.text} onChange={event => { setCandidate({ ...candidate, text: event.target.value }); try { setAccepted(new Set(payloadKeys(JSON.parse(event.target.value)))) } catch { /* incomplete JSON remains editable */ } }} spellCheck={false} />{candidate.stage === 'visual-continuity-review' && <label className="comic-visual-confirm"><input type="checkbox" checked={authorVisualInspectionConfirmed} onChange={event => setAuthorVisualInspectionConfirmed(event.target.checked)} /><span>我已查看目标页全部实际成图，并核对人物、服装、道具、空间与光线连续性。AI 当前只核对媒资元数据，不读取图片像素。</span></label>}<footer><button onClick={() => void reject()} disabled={busy}><X />放弃</button><button className="primary" onClick={() => void accept()} disabled={busy || (candidate.stage === 'visual-continuity-review' && !authorVisualInspectionConfirmed)}><Check />作者确认并采纳</button></footer></div>}
    {issues.length > 0 && <details className="comic-review-list"><summary>审查问题（{counts.issues} 项开放）</summary>{issues.map(issue => <article key={issue.id} className={issue.status}><strong>{issue.category} · {issue.severity} · {issue.pageKey}{issue.panelKey ? ` / ${issue.panelKey}` : ''}</strong><p>{issue.problem}</p><blockquote>{issue.evidence}</blockquote>{issue.status === 'open' && <button onClick={() => void (async () => { await updateComicReviewIssueStatusV1({ scope, issueId: issue.id!, status: 'dismissed' }); await reload(); await onChanged() })()}>作者驳回</button>}</article>)}</details>}
    {error && <p className="comic-pipeline-error" role="alert"><RefreshCw />{error}</p>}
  </section>
}
