import { useEffect, useMemo, useState } from 'react'
import { Eye, FilePlus2, ImagePlus, Rocket, Save, ShieldCheck, Trash2 } from 'lucide-react'
import { createAvgGame, deleteAvgGameDraft, deleteAvgMediaAsset, importAvgMediaAsset, loadAvgAuthoringSnapshot, publishAvgGame, seedAvgAcceptanceGame, updateAvgPresentation, validateAvgGame, type AvgAuthoringSnapshot } from '../../lib/avg/authoring'
import { applyAvgCue, EMPTY_AVG_STAGE, freezeAvgMediaAsset, parseAvgPresentationContent } from '../../lib/avg/runtime'
import type { AvgMediaKind, WorkspaceScope } from '../../lib/types'
import { AVG_MEDIA_KINDS } from '../../lib/types'
import { useDialog } from '../shared/Dialog'

const EMPTY: AvgAuthoringSnapshot = { definitions: [], modules: [], nodes: [], beats: [], choices: [], presentationModules: [], assets: [], releases: [] }
export default function AvgGameWorkbench({ scope }: { scope: WorkspaceScope }) {
  const dialog = useDialog()
  const [snapshot, setSnapshot] = useState(EMPTY); const [selected, setSelected] = useState<number | null>(null); const [content, setContent] = useState('{"version":1,"cues":[]}')
  const [kind, setKind] = useState<AvgMediaKind>('background'); const [assetKey, setAssetKey] = useState(''); const [alt, setAlt] = useState(''); const [source, setSource] = useState('作者本地导入'); const [license, setLicense] = useState(''); const [files, setFiles] = useState<File[]>([]); const [previewBeatKey, setPreviewBeatKey] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const refresh = async (wanted?: number | null) => { const next = await loadAvgAuthoringSnapshot(scope); setSnapshot(next); const id = wanted ?? selected ?? next.definitions[0]?.id ?? null; setSelected(id); setContent(next.presentationModules.find(row => row.gameDefinitionId === id)?.contentJson ?? '{"version":1,"cues":[]}') }
  useEffect(() => { void refresh() }, [scope.projectId, scope.worldId, scope.workId]) // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (fn: () => Promise<void>) => { setError(''); try { await fn() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  const definition = snapshot.definitions.find(item => item.id === selected)
  const beats = useMemo(() => snapshot.beats.filter(item => item.moduleId === definition?.narrativeModuleId).sort((a, b) => a.order - b.order), [definition?.narrativeModuleId, snapshot.beats])
  const timeline = useMemo(() => { try { return parseAvgPresentationContent(content) } catch { return null } }, [content])
  const latestAssets = useMemo(() => snapshot.assets.filter((asset, index, rows) => rows.findIndex(item => item.assetKey === asset.assetKey) === index).map(freezeAvgMediaAsset), [snapshot.assets])
  const previewStage = useMemo(() => {
    let stage = structuredClone(EMPTY_AVG_STAGE)
    const cues = (timeline?.cues ?? []).filter(cue => cue.beatKey === previewBeatKey).sort((a, b) => a.order - b.order)
    for (const cue of cues) stage = applyAvgCue(stage, cue, latestAssets, {})
    return stage
  }, [latestAssets, previewBeatKey, timeline])
  const totalBytes = snapshot.assets.reduce((sum, asset) => sum + asset.byteSize, 0)
  const slug = (value: string) => value.toLowerCase().replace(/\.[^.]+$/, '').replace(/[^a-z0-9._:-]+/g, '-').replace(/^-+|-+$/g, '') || 'asset'
  return <div className="avg-workbench" data-testid="avg-workbench"><aside><h3>AVG 项目</h3>{snapshot.definitions.map(def => <button className={def.id === selected ? 'active' : ''} key={def.id} onClick={() => { setSelected(def.id!); setContent(snapshot.presentationModules.find(row => row.gameDefinitionId === def.id)?.contentJson ?? '') }}>{def.title}</button>)}<button onClick={() => void run(async () => { const row = await createAvgGame({ scope }); await refresh(row.id) })}><FilePlus2 />新建</button><button onClick={() => void run(async () => { const row = await seedAvgAcceptanceGame({ scope }); await refresh(row.id); setMessage('已载入 AVG 验收样例') })}><Eye />载入演出样例</button></aside>
    <main><header><div><h2>AVG 作者工作台</h2><p>剧情真相复用 Narrative；这里只编辑本地媒资和声明式 Cue。</p></div>{selected && <><button onClick={() => void run(async () => { const report = await validateAvgGame(scope, selected); setMessage(`${report.valid ? '检查通过' : '检查失败'} · ${[...report.errors, ...report.warnings].join('；') || '无问题'}`) })}><ShieldCheck />检查</button><button onClick={() => void run(async () => { const published = await publishAvgGame({ scope, gameDefinitionId: selected }); setMessage(`已发布 GameRelease v${published.gameRelease.version}`); await refresh(selected) })}><Rocket />发布</button><button className="danger" onClick={() => void run(async () => { const confirmed = await dialog.confirm({ title: '删除 AVG 草稿？', message: '演出模块会删除；共享 Narrative、不可变发布和玩家存档保持不变。', confirmText: '删除草稿', tone: 'danger' }); if (!confirmed) return; await deleteAvgGameDraft({ scope, gameDefinitionId: selected }); await refresh(null) })}><Trash2 />删除草稿</button></>}</header>
      {error && <div role="alert">{error}</div>}{message && <div className="avg-message">{message}</div>}
      <section className="avg-author-grid"><article><h3>媒资库</h3><p>{snapshot.assets.length} 个版本 · {(totalBytes / 1024 / 1024).toFixed(2)} MB；单文件上限 100 MB，播放器预加载预算 64 MB。</p><label>稳定 key / 批量前缀<input value={assetKey} onChange={event => setAssetKey(event.target.value)} /></label><label>类型<select value={kind} onChange={event => setKind(event.target.value as AvgMediaKind)}>{AVG_MEDIA_KINDS.map(value => <option key={value}>{value}</option>)}</select></label><label>替代文本<input value={alt} onChange={event => setAlt(event.target.value)} /></label><label>来源<input value={source} onChange={event => setSource(event.target.value)} /></label><label>授权说明<input value={license} onChange={event => setLicense(event.target.value)} /></label><input aria-label="选择媒资文件" type="file" multiple onChange={event => setFiles(Array.from(event.target.files ?? []))} /><button disabled={files.length === 0 || (files.length === 1 && !assetKey.trim())} onClick={() => void run(async () => { for (const file of files) { const key = files.length === 1 ? assetKey.trim() : `${assetKey.trim() || kind}.${slug(file.name)}`; await importAvgMediaAsset({ scope, assetKey: key, kind, name: file.name, blob: file, altText: alt || (kind.startsWith('character') || ['background', 'cg', 'ui'].includes(kind) ? file.name : ''), source, license }) } setMessage(`已导入 ${files.length} 个媒资版本`); setFiles([]); await refresh(selected) })}><ImagePlus />{files.length > 1 ? `批量导入 ${files.length} 项` : '导入新版本'}</button><ul>{snapshot.assets.map(asset => <li key={asset.id}><div><code>{asset.assetKey}@{asset.version}</code><span>{asset.kind} · {asset.byteSize} B</span></div><button aria-label={`删除 ${asset.assetKey}@${asset.version}`} onClick={() => void run(async () => { const confirmed = await dialog.confirm({ title: `删除 ${asset.assetKey}@${asset.version}？`, message: '仍被草稿或不可变发布引用时系统会拒绝删除。', confirmText: '删除媒资', tone: 'danger' }); if (!confirmed) return; await deleteAvgMediaAsset({ scope, mediaAssetId: asset.id! }); await refresh(selected) })}><Trash2 /></button></li>)}</ul></article>
      <article><h3>声明式演出时间线</h3><p>支持背景、立绘、CG、转场、移动、镜头、摇晃、闪白和四类音频；只接受白名单 Cue，不接受脚本。</p><textarea rows={18} value={content} onChange={event => setContent(event.target.value)} /><button disabled={!selected} onClick={() => void run(async () => { parseAvgPresentationContent(content); await updateAvgPresentation({ scope, gameDefinitionId: selected!, content }); setMessage('演出时间线已保存'); await refresh(selected) })}><Save />保存时间线</button><div className="avg-cue-preview"><h3>从任意 Beat 预览</h3><select aria-label="演出预览 Beat" value={previewBeatKey} onChange={event => setPreviewBeatKey(event.target.value)}><option value="">选择 Beat</option>{beats.map(beat => <option key={beat.beatKey} value={beat.beatKey}>{beat.beatKey} · {beat.text.slice(0, 28)}</option>)}</select>{previewBeatKey && <><p>{timeline?.cues.filter(cue => cue.beatKey === previewBeatKey).length ?? 0} 条 Cue；预览只投影演出状态，不写 Narrative 或 SIM。</p><dl><dt>背景</dt><dd>{previewStage.backgroundAssetKey ?? '无'}</dd><dt>CG</dt><dd>{previewStage.cgAssetKey ?? '无'}</dd><dt>角色</dt><dd>{previewStage.actors.map(actor => `${actor.actorKey}:${actor.assetKey}@${actor.slot}`).join(' · ') || '无'}</dd><dt>音频</dt><dd>{previewStage.activeAudio.map(audio => `${audio.channel}:${audio.assetKey}`).join(' · ') || '无'}</dd><dt>镜头</dt><dd>{previewStage.camera.x}, {previewStage.camera.y}, ×{previewStage.camera.scale}</dd></dl></>}</div></article></section>
    </main></div>
}
