import type { RuleNumberExpressionV1, RulePackV1 } from "../types";
import { parseRulePackV1, runRulePackFixturesV1 } from "./rule-pack";

const constant = (value: number): RuleNumberExpressionV1 => ({
  op: "constant",
  value,
});
const attribute = (key: string): RuleNumberExpressionV1 => ({
  op: "attribute",
  key,
});
const add = (...values: RuleNumberExpressionV1[]): RuleNumberExpressionV1 => ({
  op: "add",
  values,
});
const floorDivide = (
  value: RuleNumberExpressionV1,
  divisor: number,
): RuleNumberExpressionV1 => ({ op: "floor-divide", value, divisor });
const unlimited = () => ({
  mode: "unlimited" as const,
  maximum: null,
  resourceKey: null,
  cost: null,
  sharedPoolKey: null,
  cooldownRounds: null,
  reset: [],
});
const itemMechanics = (category: string) => ({
  category,
  stackPolicy: "unique" as const,
  maxStack: 1,
  weight: null,
  equipSlots: [],
  requiresAttunement: false,
  maximumCharges: null,
  maximumDurability: null,
});

const PERCENT_TRAITS = [
  "investigation",
  "observation",
  "influence",
  "agility",
  "force",
  "resolve",
] as const;

/** StoryForge-owned d100 investigation rules; no third-party setting text. */
export const STORYFORGE_D100_INVESTIGATION_RULE_PACK_V1: RulePackV1 = {
  schema: "storyforge.rule-pack",
  version: 1,
  ruleSystemId: "storyforge.d100-investigation",
  ruleSystemVersion: "1.0.0",
  title: "StoryForge d100 调查规则",
  description:
    "面向悬疑、犯罪、惊险与关系调查的第一方百分骰规则。每项关键行动以 1d100 对照角色能力，完整区分大成功、极难成功、困难成功、成功、失败和大失败。",
  license: {
    licenseId: "storyforge-d100-first-party-1.0",
    name: "StoryForge d100 第一方内容许可",
    attribution:
      "StoryForge d100 Investigation original rules; copyright StoryForge contributors.",
    commercialUse: true,
    derivativesAllowed: true,
    sourceUrl: null,
  },
  attributes: [
    {
      key: "investigation",
      name: "调查",
      description: "搜证、研究、复原事件与发现关联。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
    {
      key: "observation",
      name: "观察",
      description: "察觉异常、读取环境与判断他人反应。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
    {
      key: "influence",
      name: "影响",
      description: "说服、欺瞒、安抚、威慑与建立信任。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
    {
      key: "agility",
      name: "灵巧",
      description: "潜行、闪避、追逐、驾驶与精密操作。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
    {
      key: "force",
      name: "体魄",
      description: "力量、耐力、格斗与承受伤害。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
    {
      key: "resolve",
      name: "定力",
      description: "面对恐惧、压力、诱惑和长期消耗时保持自我。",
      minimum: 1,
      maximum: 99,
      defaultValue: 50,
    },
  ],
  derivedStats: [
    {
      key: "initiative",
      name: "先机",
      description: "以灵巧的十分之一决定行动先后。",
      formula: floorDivide(attribute("agility"), 10),
      minimum: 0,
      maximum: 9,
    },
    {
      key: "defense",
      name: "防护",
      description: "面对直接危险时的简化防护值。",
      formula: add(constant(5), floorDivide(attribute("agility"), 10)),
      minimum: 5,
      maximum: 14,
    },
    {
      key: "load",
      name: "负重格",
      description: "可便利携带的重要物品数量。",
      formula: add(constant(2), floorDivide(attribute("force"), 10)),
      minimum: 2,
      maximum: 11,
    },
  ],
  diceModels: [
    {
      key: "percentile",
      name: "百分骰 d100",
      count: 1,
      sides: 100,
      keep: "all",
    },
    { key: "impact-d6", name: "影响 d6", count: 1, sides: 6, keep: "all" },
  ],
  checks: [
    {
      key: "percent-check",
      name: "百分能力检定",
      diceModelKey: "percentile",
      attributeKeys: [...PERCENT_TRAITS],
      resolver: {
        mode: "roll-under",
        defaultDifficulty: null,
        hardDivisor: 2,
        extremeDivisor: 5,
        criticalSuccessMaximum: 1,
        criticalFailureMinimum: 96,
      },
    },
  ],
  resources: [
    {
      key: "vigor",
      name: "体力",
      description: "伤势、疲劳与追逐消耗。",
      maximumFormula: add(constant(8), floorDivide(attribute("force"), 10)),
      initialMode: "maximum",
      minimum: 0,
    },
    {
      key: "composure",
      name: "镇定",
      description: "承受恐惧、压力与关系冲击的能力。",
      maximumFormula: add(constant(8), floorDivide(attribute("resolve"), 10)),
      initialMode: "maximum",
      minimum: 0,
    },
    {
      key: "insight",
      name: "洞见",
      description: "推动线索串联、协助和重构假说的稀缺资源。",
      maximumFormula: add(
        constant(1),
        floorDivide(attribute("investigation"), 25),
      ),
      initialMode: "maximum",
      minimum: 0,
    },
  ],
  conditions: [
    {
      key: "prepared",
      name: "准备充分",
      description: "相关百分检定阈值 +10。",
      stacking: "replace",
      maximumStacks: 1,
      defaultDurationRounds: 1,
      checkModifier: 10,
    },
    {
      key: "pressured",
      name: "承压",
      description: "相关百分检定阈值 -10。",
      stacking: "replace",
      maximumStacks: 1,
      defaultDurationRounds: 1,
      checkModifier: -10,
    },
    {
      key: "shaken",
      name: "动摇",
      description: "持续心理压力；可叠加，直到安全休整或效果移除。",
      stacking: "stack",
      maximumStacks: 3,
      defaultDurationRounds: null,
      checkModifier: -5,
    },
  ],
  actions: [
    {
      key: "investigate",
      name: "搜证与研究",
      description: "检查现场、比对资料或重构事件。关键线索遵循失败推进。",
      phase: "action",
      target: "scene",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        {
          kind: "check",
          checkKey: "percent-check",
          attributeKey: "investigation",
        },
      ],
    },
    {
      key: "observe",
      name: "观察与洞察",
      description: "发现异常、尾随迹象或他人的情绪变化。",
      phase: "action",
      target: "scene",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        {
          kind: "check",
          checkKey: "percent-check",
          attributeKey: "observation",
        },
      ],
    },
    {
      key: "influence",
      name: "接触与交涉",
      description: "建立信任、套取信息、施压或平息冲突。",
      phase: "action",
      target: "single-enemy",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        { kind: "check", checkKey: "percent-check", attributeKey: "influence" },
      ],
    },
    {
      key: "evade",
      name: "闪避与追逐",
      description: "脱离危险、潜行穿越或在追逐中夺取位置。",
      phase: "action",
      target: "scene",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        { kind: "check", checkKey: "percent-check", attributeKey: "agility" },
      ],
    },
    {
      key: "force",
      name: "强行突破",
      description: "以体魄突破障碍、搬运重物或承受环境伤害。",
      phase: "action",
      target: "scene",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        { kind: "check", checkKey: "percent-check", attributeKey: "force" },
      ],
    },
    {
      key: "steady",
      name: "稳住心神",
      description: "面对恐惧、压力或诱导时保持判断。",
      phase: "action",
      target: "self",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        { kind: "check", checkKey: "percent-check", attributeKey: "resolve" },
      ],
    },
    {
      key: "confront",
      name: "正面冲突",
      description: "体魄检定成功后造成 d6 体力伤害。",
      phase: "action",
      target: "single-enemy",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [
        { kind: "check", checkKey: "percent-check", attributeKey: "force" },
        {
          kind: "damage",
          resourceKey: "vigor",
          diceModelKey: "impact-d6",
          modifierAttributeKey: null,
        },
      ],
    },
    {
      key: "connect-clues",
      name: "串联线索",
      description: "消耗 1 洞见，将已有证据组织成可验证的新假说。",
      phase: "action",
      target: "scene",
      costResourceKey: null,
      costAmount: 0,
      usage: {
        mode: "resource-cost",
        maximum: null,
        resourceKey: "insight",
        cost: 1,
        sharedPoolKey: null,
        cooldownRounds: null,
        reset: [],
      },
      effects: [],
    },
    {
      key: "assist",
      name: "准备协助",
      description: "用行动让一名同伴在下一次相关检定中准备充分。",
      phase: "action",
      target: "single-ally",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [{ kind: "condition", conditionKey: "prepared", stacks: 1 }],
    },
    {
      key: "warn",
      name: "及时警告",
      description: "以反应提醒同伴，使其获得短暂准备。",
      phase: "reaction",
      target: "single-ally",
      costResourceKey: null,
      costAmount: 0,
      usage: unlimited(),
      effects: [{ kind: "condition", conditionKey: "prepared", stacks: 1 }],
    },
    {
      key: "recover",
      name: "安全休整",
      description: "在安全幕间恢复 2 点体力和 2 点镇定；每场景一次。",
      phase: "downtime",
      target: "self",
      costResourceKey: null,
      costAmount: 0,
      usage: {
        mode: "charges",
        maximum: 1,
        resourceKey: null,
        cost: null,
        sharedPoolKey: null,
        cooldownRounds: null,
        reset: ["scene", "long-rest"],
      },
      effects: [
        { kind: "resource", resourceKey: "vigor", delta: 2 },
        { kind: "resource", resourceKey: "composure", delta: 2 },
      ],
    },
  ],
  turnStructure: {
    initiativeDiceModelKey: "percentile",
    initiativeAttributeKey: "initiative",
    phases: ["start", "action", "end"],
    actionsPerTurn: 1,
    reactionsPerRound: 1,
  },
  items: [
    {
      key: "field-kit",
      name: "现场调查箱",
      description: "取样、记录、照明与基础检测工具。",
      tags: ["tool", "investigation"],
      grantedActionKeys: ["investigate", "observe", "connect-clues"],
      mechanics: itemMechanics("tool"),
    },
    {
      key: "recording-device",
      name: "记录设备",
      description: "保存访谈、环境与时间线证据的便携设备。",
      tags: ["tool", "evidence"],
      grantedActionKeys: ["observe", "influence"],
      mechanics: itemMechanics("evidence"),
    },
    {
      key: "protective-gear",
      name: "防护装备",
      description: "用于危险现场的基础防护与急救用品。",
      tags: ["armor", "medical"],
      grantedActionKeys: ["force", "confront", "recover"],
      mechanics: itemMechanics("armor"),
    },
  ],
  advancement: {
    currencyKey: "growth",
    currencyName: "成长点",
    awardPerMilestone: 2,
    attributeIncreaseCost: 2,
    maximumAttributeValue: 99,
    progressionModel: "classless",
    skillIncreaseCost: 1,
    maximumSkillValue: 99,
    levelIncreaseCost: 5,
    maximumLevel: 20,
    rankOrder: [],
    rankIncreaseCost: 4,
  },
  characterSheetUi: {
    sections: [
      { key: "percent", title: "百分能力", fieldKeys: [...PERCENT_TRAITS] },
      {
        key: "derived",
        title: "派生值",
        fieldKeys: ["initiative", "defense", "load"],
      },
      {
        key: "resources",
        title: "资源",
        fieldKeys: ["vigor", "composure", "insight"],
      },
    ],
  },
  compendium: [
    {
      key: "d100.core",
      title: "百分检定",
      category: "check",
      body: "掷 1d100；结果不高于当前能力阈值即成功。公开修正改变阈值而不改写骰点，阈值始终限制在 1～100。",
      relatedKeys: ["percentile", "percent-check"],
    },
    {
      key: "d100.degrees",
      title: "成功等级",
      category: "check",
      body: "不高于阈值的二分之一为困难成功，不高于五分之一为极难成功，结果 1 为大成功；高位失败可形成大失败。",
      relatedKeys: ["percent-check"],
    },
    {
      key: "d100.clues",
      title: "失败也推进调查",
      category: "core",
      body: "关键线索不可被单次失败永久锁死。失败会让角色获得不完整信息、付出资源、推进危险时钟或暴露位置。",
      relatedKeys: ["investigate", "connect-clues"],
    },
    {
      key: "d100.pressure",
      title: "体力与镇定",
      category: "condition",
      body: "身体后果进入体力，心理与关系压力进入镇定；归零触发场景后果，但不允许叙事层跳过账本。",
      relatedKeys: ["vigor", "composure", "shaken"],
    },
    {
      key: "d100.growth",
      title: "无职业成长",
      category: "advancement",
      body: "里程碑奖励成长点，玩家可以提高已有能力或技能，所有花费、上限和选择进入成长账本。",
      relatedKeys: [...PERCENT_TRAITS],
    },
    {
      key: "d100.safety",
      title: "调查题材安全",
      category: "safety",
      body: "在 Session Zero 中明确禁区、淡出项和内容警告；任何玩家都可暂停或离桌，无需解释私人原因。",
      relatedKeys: [],
    },
  ],
  migrations: [],
  tests: [
    {
      fixtureKey: "balanced-investigator",
      attributes: {
        investigation: 50,
        observation: 50,
        influence: 50,
        agility: 50,
        force: 50,
        resolve: 50,
      },
      expectedDerivedStats: { initiative: 5, defense: 10, load: 7 },
      expectedResourceMaximums: { vigor: 13, composure: 13, insight: 3 },
    },
    {
      fixtureKey: "specialist-investigator",
      attributes: {
        investigation: 80,
        observation: 70,
        influence: 35,
        agility: 45,
        force: 30,
        resolve: 65,
      },
      expectedDerivedStats: { initiative: 4, defense: 9, load: 5 },
      expectedResourceMaximums: { vigor: 11, composure: 14, insight: 4 },
    },
  ],
};

export function createD100InvestigationRulePackV1(): RulePackV1 {
  const pack = parseRulePackV1(STORYFORGE_D100_INVESTIGATION_RULE_PACK_V1);
  runRulePackFixturesV1(pack);
  return pack;
}
