import { useEffect, useRef, useState } from 'react'
import { liveQuery } from 'dexie'
import { db } from '../../lib/db/schema'
import { resolveScopeLike } from '../../lib/workspace/scope'
import type { WorkspaceScope } from '../../lib/types'
import { connectExtensionMcp } from '../../lib/extensions/mcp-client'
import { executeExtensionTool, previewExtensionTool, readExtensionToolRun, refreshExtensionToolRun } from '../../lib/extensions/mcp-run'
import type { ExtensionReviewRequest } from '../../lib/extensions/types'

type Preview = Awaited<ReturnType<typeof previewExtensionTool>>
type Saved = Awaited<ReturnType<typeof readExtensionToolRun>>
export default function PluginTools({ projectId, workId, request }: { projectId: number; workId?: number; request?: ExtensionReviewRequest }) {
  const [scope,setScope]=useState<WorkspaceScope>(),[preview,setPreview]=useState<Preview>(),[saved,setSaved]=useState<Saved>(),[runs,setRuns]=useState<{id:number;name:string}[]>([])
  const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const controller=useRef<AbortController|null>(null)
  useEffect(()=>()=>controller.current?.abort(),[])
  useEffect(()=>{let active=true;setPreview(undefined);setSaved(undefined);setToken('');const load=async()=>{const project=await db.projects.get(projectId),work=await db.works.get(workId??project?.activeWorkId??-1);if(!work||work.projectId!==projectId)throw new Error('请先选择作品');const scope=await resolveScopeLike({projectId,workId:work.id!,worldId:work.worldId});if(active)setScope(scope);if(request){const value=await previewExtensionTool(request);if(active)setPreview(value)}};void load().catch(e=>active&&setError(String(e)));return()=>{active=false;controller.current?.abort()}},[projectId,workId,request])
  useEffect(()=>{if(!scope)return;const sub=liveQuery(async()=>(await db.agentRuns.where('projectId').equals(projectId).toArray()).filter(row=>row.workId===scope.workId&&row.contractJson.includes('"extension-mcp-v1"')).sort((a,b)=>b.createdAt-a.createdAt).map(row=>({id:row.id!,name:JSON.parse(row.contractJson).objective as string}))).subscribe({next:setRuns,error:e=>setError(String(e))});return()=>sub.unsubscribe()},[projectId,scope])
  async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function execute(cancel=false){const value=saved?.checkpoint??preview?.checkpoint;if(!value||!scope)return;if(saved?.historicalOnly)throw new Error('历史副本只能查看');controller.current=new AbortController();const connection=await connectExtensionMcp(value.connector,{token:token||undefined,signal:controller.current.signal});try{const run=saved?await refreshExtensionToolRun(scope,saved.snapshot.run.id,connection,cancel,controller.current.signal):await executeExtensionTool(request!,preview!.hash,connection,controller.current.signal);setSaved(await readExtensionToolRun(scope,run.run.id));setMessage(run.projection.state==='completed'?'工具结果已保存。':'任务状态已保存，可稍后继续查看。')}finally{await connection.close()}}
  const value=saved?.checkpoint??preview?.checkpoint
  return <section className="sf-extension-surface" aria-label="外部工具与任务"><h3>外部工具与任务</h3><p>执行前检查将发送的内容。工具结果保存为参考，不会自动写入作品。长任务按已有任务标识查询，刷新不会重复执行。</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{value&&<><h4>{value.connector.title} · {value.tool}</h4><p>服务：{value.connector.url} · 协议：{value.connector.protocol}</p><details><summary>将发送的参数</summary><pre>{JSON.stringify(value.input,null,2)}</pre></details>{!saved?.historicalOnly&&<label>访问令牌（如服务需要，仅本次页面使用）<input type="password" autoComplete="off" aria-label="工具访问令牌" value={token} onChange={e=>setToken(e.target.value)}/></label>}{saved?.checkpoint.result!==undefined&&<pre aria-label="工具执行结果">{JSON.stringify(saved.checkpoint.result,null,2)}</pre>}{saved?.checkpoint.reference&&<p>外部任务 {saved.checkpoint.reference.taskId} · {saved.checkpoint.remoteStatus}</p>}{saved?.historicalOnly?<p>历史副本（只读）：保留原任务参数和结果，不会查询、取消或重复执行原任务。</p>:!saved?<button disabled={busy} onClick={()=>void act(()=>execute())}>确认执行一次工具</button>:saved.checkpoint.reference&&!['completed','failed','cancelled'].includes(saved.snapshot.projection.state)?<div className="sf-extension-actions"><button disabled={busy} onClick={()=>void act(()=>execute())}>查询已有任务</button><button disabled={busy} onClick={()=>void act(()=>execute(true))}>取消外部任务</button></div>:saved.checkpoint.result===undefined?<p>结果未知；此页面不会重发原始请求，请在外部服务核实。</p>:null}{busy&&<button onClick={()=>controller.current?.abort()}>停止等待</button>}</>}
  <div className="sf-extension-actions">{runs.map(run=><button key={run.id} disabled={busy} onClick={()=>void act(async()=>{setSaved(await readExtensionToolRun(scope!,run.id));setPreview(undefined);setToken('')})}>{run.name}</button>)}</div>{!runs.length&&!preview&&<p>此作品还没有外部工具执行记录。</p>}<small>支持 Streamable HTTP 与可选本机桥。Apps 界面、文件根目录、服务端采样及额外交互授权当前不启用。</small></section>
}
