import { lazy, Suspense, useEffect, useState } from 'react'
import { liveQuery } from 'dexie'
import { db } from '../../lib/db/schema'
import type { HomeData } from './useHomeData'
import { runWorkPath, RUN_LABELS, runSummary, type HomeWork } from '../../lib/home/catalog'
import { searchHome, type HomeSearchHit } from '../../lib/home/search'
import { updateWorkCover } from '../../lib/workspace/works'
import { importProjectJSON, type ProjectExportData } from '../../lib/export/json-export'
import { readProjectJSONFile } from '../../lib/export/json-file'
import { inspectProjectBackup } from '../../lib/export/backup-trust'
import { isFSASupported, pickFolder, ensureFolderPermission, readStoryforgeBackups } from '../../lib/storage/folder-backup'
import { useDialog } from '../shared/Dialog'
const DataManagement=lazy(()=>import('../data/DataManagementPanel'))
export type HomeOpen=(path:string,row?:HomeWork)=>Promise<void>
const Empty=({children}:{children:React.ReactNode})=><p className="home-empty">{children}</p>
export function HomeSearch({data,open}:{data:HomeData;open:HomeOpen}){
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[work,setWork]=useState(''),[result,setResult]=useState<{items:HomeSearchHit[];truncated:boolean}>({items:[],truncated:false}),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{setLoading(true);setError('');const sub=liveQuery(()=>searchHome(query,kind,Number(work)||undefined)).subscribe({next:r=>{setResult(r);setLoading(false)},error:e=>{setError(String(e));setLoading(false)}});return()=>sub.unsubscribe()},[query,kind,work])
 return <section className="lf-paper"><h3>搜索本地内容</h3><p>检索作品、世界草稿、正文、人物和设定。已发布世界版本的原文检索请进入世界引擎的数据出口。</p><form className="home-filters" onSubmit={e=>{e.preventDefault();setQuery(input.trim())}}><input aria-label="搜索内容" value={input} onChange={e=>setInput(e.target.value)} placeholder="输入人物、文字或作品名称"/><select aria-label="搜索类型" value={kind} onChange={e=>setKind(e.target.value)}>{[['all','全部类型'],['works','作品'],['worlds','世界'],['chapters','正文'],['characters','人物'],['settings','设定']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><select aria-label="搜索范围" value={work} onChange={e=>setWork(e.target.value)}><option value="">全部本地创作</option>{data.rows.map(r=><option key={r.work.id} value={r.work.id}>{r.work.title}</option>)}</select><button className="lf-action lf-action-primary" disabled={loading}>搜索</button></form>{error&&<p role="alert">{error}</p>}{loading?<p role="status">正在检索…</p>:!query?<Empty>输入关键词后开始检索。</Empty>:!result.items.length?<Empty>没有找到匹配内容，试试其他关键词或范围。</Empty>:<><p>{result.items.length} 条结果{result.truncated?' · 已展示前 100 条，请缩小范围':''}</p>{result.items.map(hit=><article className="home-search-hit" key={hit.key}><small>{hit.row?.work.title??'世界引擎'} · {({works:'作品',worlds:'世界草稿',chapters:'正文',characters:'人物',settings:'设定'} as Record<string,string>)[hit.kind]}</small><h4>{hit.title}</h4><p>{hit.excerpt}</p><button className="lf-action" onClick={()=>void open(hit.path,hit.row)}>查看内容</button></article>)}</>}</section>
}
export function HomeTasks({data,open,runId}:{data:HomeData;open:HomeOpen;runId:number}){
 const [filter,setFilter]=useState('attention'),[events,setEvents]=useState<{type:string;createdAt:number}[]>([])
 const attention=['awaiting_confirmation','paused','failed','recovery_required'],running=['planned','running','verifying','recovering']
 const selected=data.runs.find(r=>r.id===runId)
 useEffect(()=>{setEvents([]);if(!selected)return;const sub=liveQuery(()=>db.agentRunEvents.where('runId').equals(selected.id!).toArray()).subscribe(rows=>setEvents(rows.sort((a,b)=>b.createdAt-a.createdAt).slice(0,20)));return()=>sub.unsubscribe()},[selected])
 const rows=data.runs.filter(r=>filter==='all'||(filter==='attention'?attention:filter==='running'?running:['completed','cancelled']).includes(r.status))
 return <><section className="lf-paper"><h3>创作任务</h3><p>汇总已持久化的创作与制作任务。生成结果的采纳、重试和恢复，在所属产品内确认；游玩回合仍在各产品的存档中查看。</p><div className="lf-subtabs">{[['attention','待处理'],['running','进行中'],['done','已结束'],['all','全部']].map(([id,title])=><button key={id} aria-current={filter===id?'page':undefined} onClick={()=>setFilter(id)}>{title} · {data.runs.filter(r=>id==='all'||(id==='attention'?attention:id==='running'?running:['completed','cancelled']).includes(r.status)).length}</button>)}</div>{!rows.length&&<Empty>这个分类中没有任务。</Empty>}{rows.map(run=>{const row=data.rows.find(r=>r.work.id===run.workId)!;return <article className="home-task" key={run.id}><div><small>{row.work.title} · {new Date(run.updatedAt).toLocaleString()}</small><h4>{runSummary(run).title}</h4><span className="home-tag">{RUN_LABELS[run.status]}</span></div><button className="lf-action" onClick={()=>void open(`/home/tasks?run=${run.id}`)}>查看任务</button></article>})}</section>
 {!!runId&&!selected&&<section className="lf-paper"><p role="alert">这条任务已被移除或不属于当前本地创作，请从列表重新选择。</p></section>}
 {selected&&<section className="lf-paper" aria-label="任务详情"><h3>{runSummary(selected).title}</h3><p>{RUN_LABELS[selected.status]} · 最近事件 {selected.lastSequence} · {selected.terminalReceiptHash?'已记录终态回执':'尚无终态回执'}</p><p>先查看运行状态，再回到原工作台检查候选和恢复条件。这里不会直接采纳或重新调用模型。</p><button className="lf-action lf-action-primary" onClick={()=>{const row=data.rows.find(r=>r.work.id===selected.workId)!;void open(runWorkPath(row,selected),row)}}>打开所属作品</button><details><summary>运行证据与最近事件</summary><p>任务 #{selected.id} · 合约校验 {selected.contractHash}</p>{events.map((event,i)=><p key={i}>{new Date(event.createdAt).toLocaleString()} · {event.type}</p>)}</details></section>}
 {!!data.imports.length&&<section className="lf-paper"><h3>文档导入记录</h3>{data.imports.map(job=><article className="home-task" key={job.id}><div><h4>{job.filename||'粘贴的文档'}</h4><p>{({parsing:'解析中',ready:'待确认',imported:'已导入',discarded:'已放弃',failed:'失败'})[job.status]}{job.errorMessage?` · ${job.errorMessage}`:''}</p></div><button className="lf-action" onClick={()=>void open(`/home/data?project=${job.projectId}`)}>查看所属工作区</button></article>)}</section>}</>
}
export function HomeCover({row}:{row:HomeWork}){
 const [candidate,setCandidate]=useState(row.work.coverImage||''),[expected,setExpected]=useState(row.work.updatedAt),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const upload=async(file?:File)=>{if(!file)return;setMessage('');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('请选择 5 MB 以内的 PNG、JPEG 或 WebP。');const bitmap=await createImageBitmap(file);const pixels=bitmap.width*bitmap.height;bitmap.close();if(pixels>20_000_000)throw new Error('图片尺寸过大，请缩小到 2000 万像素以内。');const reader=new FileReader();reader.onload=()=>setCandidate(String(reader.result));reader.onerror=()=>setMessage('图片读取失败');reader.readAsDataURL(file)}catch(e){setMessage(e instanceof DOMException?'无法读取这张图片，请选择有效的 PNG、JPEG 或 WebP 文件。':String(e))}}
 const save=async()=>{setBusy(true);setMessage('');try{const updatedAt=await updateWorkCover({projectId:row.work.projectId,worldId:row.work.worldId,workId:row.work.id!},candidate,expected);setExpected(updatedAt);setMessage('封面已保存。')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className="lf-paper home-cover-editor"><div><h3>{row.work.title}</h3>{candidate?<img className="home-cover-large" src={candidate} alt={`${row.work.title}的封面预览`}/>:<div className="home-book home-cover-large">{row.work.title}</div>}</div><div><h3>作品封面</h3><p>上传后先预览，确认保存才会更新这部作品。封面随完整作品备份一同保存。</p><label className="lf-action">选择封面<input aria-label="上传封面" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></label><div className="home-actions"><button className="lf-action" onClick={()=>setCandidate('')}>移除封面</button><button className="lf-action lf-action-primary" disabled={busy} onClick={()=>void save()}>{busy?'正在保存…':'保存封面'}</button></div><p role="status">{message}</p><button className="home-text-button" onClick={()=>{setCandidate(row.work.coverImage||'');setExpected(row.work.updatedAt);setMessage('已重新读取当前封面。')}}>重新读取已保存封面</button><p>书脊、封底、印刷装帧和封面生成历史尚未开放。</p></div></section>
}
export function HomeBackup({data,projectId,open}:{data:HomeData;projectId:number;open:HomeOpen}){
 const dialog=useDialog(),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const project=data.projects.find(p=>p.id===projectId)
 const importData=async(input:unknown)=>{const report=inspectProjectBackup(input);if(!report.valid)throw new Error(report.errors.join('；'));if(!await dialog.confirm({title:'导入完整备份？',message:'校验已通过。将创建独立工作区副本，保留现有作品。',confirmText:'确认导入'}))return;const id=await importProjectJSON(input as ProjectExportData);await open(`/home/data?project=${id}`)}
 const importFile=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{await importData(await readProjectJSONFile(file))}catch(e){setError(String(e))}finally{setBusy(false)}}
 const folder=async()=>{setBusy(true);setError('');try{if(!isFSASupported())throw new Error('当前浏览器不支持文件夹恢复，请使用 Chrome 或 Edge，或导入 JSON 备份。');const dir=await pickFolder();if(!dir)return;if(!await ensureFolderPermission(dir,false))throw new Error('没有文件夹读取权限。');const files=await readStoryforgeBackups(dir);if(!files.length)throw new Error('没有找到可恢复的备份。');for(const file of files)await importData(file.data)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <><section className="lf-paper"><h3>数据与备份</h3><p>先选择工作区，再导出、创建快照或处理文件夹变化。没有本地作品时，也可以导入已有备份。</p><label>工作区<select aria-label="备份工作区" value={projectId||''} onChange={e=>void open(`/home/data${e.target.value?`?project=${e.target.value}`:''}`)}><option value="">选择工作区</option>{data.projects.map(p=><option key={p.id} value={p.id}>{data.rows.find(r=>r.work.id===p.activeWorkId)?.work.title||data.worlds.find(w=>w.id===p.activeWorldId)?.name||`工作区 ${p.id}`}</option>)}</select></label><div className="home-actions"><label className="lf-action">导入 JSON 备份<input aria-label="导入 JSON 备份" disabled={busy} type="file" accept=".json,application/json" onChange={e=>void importFile(e.target.files?.[0])}/></label><button className="lf-action" disabled={busy} onClick={()=>void folder()}>从备份文件夹恢复</button></div>{busy&&<p role="status">正在读取、校验或恢复备份，请保持页面打开…</p>}{error&&<p role="alert">{error}</p>}</section>{project?<section className="lf-paper home-embedded"><Suspense fallback={<p>读取备份功能…</p>}><DataManagement key={project.id} project={project} onImported={id=>void open(`/home/data?project=${id}`)} onOpenStorageSettings={()=>void open(`/home/settings?project=${project.id}`)}/></Suspense></section>:<section className="lf-paper"><Empty>选择工作区后显示该工作区的真实备份、快照和授权状态。</Empty></section>}</>
}
