// Keep navigation structure in config.mts; this dictionary only translates labels.
export const enLabels: Record<string, string> = {
  '开始使用': 'Getting started',
  '概览': 'Overview',
  'StoryForge 是什么': 'What is StoryForge?',
  '根据目标选择产品': 'Choose a product',
  '五分钟上手': 'Quick start',
  '安装与启动': 'Install and launch',
  '模型与 API 配置': 'Models and APIs',
  '文档站说明': 'About these docs',
  '功能指南': 'Feature guides',
  '功能指南概览': 'Feature overview',
  '当前产品能力': 'Current capabilities',
  '分步骤长篇': 'Step-by-step longform',
  '长篇完整流程': 'Complete longform workflow',
  '设定、人物与故事设计': 'Settings, characters, and story design',
  '大纲、细纲与正文': 'Outlines, scene beats, and prose',
  '连续性与改稿': 'Continuity and revision',
  '文风学习与校准': 'Style learning and calibration',
  '项目参考与作品分析': 'References and work analysis',
  '角色驱动剧情': 'Character-driven plotting',
  '伏笔、事实与认知': 'Foreshadowing, facts, and knowledge',
  '多世界、地点与地图': 'Multiple worlds, locations, and maps',
  '短篇小说': 'Short fiction',
  '小说转剧本': 'Novel to screenplay',
  '小说转漫画': 'Novel to comic',
  '漫剧素材与前期生产': 'Motion-comic preproduction',
  '世界引擎': 'World engine',
  '节点创作（预览）': 'Node authoring (preview)',
  '互动产品（预览）': 'Interactive products (preview)',
  '共同流程与边界': 'Shared flow and boundaries',
  '跑团与 AI KP': 'TTRPGs and AI game mastering',
  '角色聊天': 'Character chat',
  'AI 小镇': 'AI town',
  'AVG 与视觉小说': 'AVG and visual novels',
  '文字冒险（开发中）': 'Text adventure (in development)',
  '文字开放世界（开发中）': 'Text open world (in development)',
  '本地记忆工作区': 'Local memory workspace',
  '核心概念': 'Core concepts',
  '核心概念概览': 'Concept overview',
  '项目、作品与世界': 'Projects, works, and worlds',
  '封存、制作、发布与存档': 'Sealing, production, releases, and saves',
  '使用指南': 'Usage guides',
  '使用指南概览': 'Usage overview',
  '内置作品与示例': 'Built-in works and examples',
  '导入小说与参考资料': 'Import fiction and references',
  'AI 候选、确认与恢复': 'AI candidates, confirmation, and recovery',
  '保存、备份与恢复': 'Saving, backup, and recovery',
  '导出、交付与分享': 'Export, delivery, and sharing',
  '费用、Token 与省钱方法': 'Costs, tokens, and saving money',
  '本地数据与隐私': 'Local data and privacy',
  '如何使用 Prompt': 'Using Prompts',
  '故障排查': 'Troubleshooting',
  '常见问题': 'FAQ',
  'Prompt 与创作方法': 'Prompts and methods',
  'Prompt 资料库说明': 'About the Prompt library',
  'A · 总蓝图与规范': 'A · Blueprint and standards',
  '小说 Prompt 体系总目录': 'Fiction Prompt system index',
  'A-1 总蓝图': 'A-1 Master blueprint',
  'A-2 资产结构与质量闸门': 'A-2 Asset structure and quality gates',
  'B · Prompt 方法论与元提示词': 'B · Methodology and meta-Prompts',
  '小说创作 Prompt 方法论基础': 'Fiction Prompt methodology foundations',
  'B-1 创作型 Prompt 构造规则': 'B-1 Creative Prompt construction',
  'B-2 创作型 Prompt 构建器': 'B-2 Creative Prompt builder',
  'B-3 素材与 Prompt 适配器': 'B-3 Material and Prompt adapter',
  'B-4 Prompt 审查诊断与优化': 'B-4 Prompt audit and optimization',
  'B-5 Prompt 仿写与语义保真': 'B-5 Prompt adaptation and semantic fidelity',
  'B-6 优质 Prompt 逆向拆解': 'B-6 Reverse-engineer quality Prompts',
  'B-7 Prompt 流水线规划': 'B-7 Prompt pipeline planning',
  'B-8 SFT 优改差异归因': 'B-8 SFT revision attribution',
  'B-9 脚本反向 Prompt 构建': 'B-9 Reverse-build Prompts from scripts',
  'B-10 漫剧方法迁移到小说': 'B-10 Transfer motion-comic methods to fiction',
  'C · 小说创作流水线': 'C · Fiction pipeline',
  '调用指南': 'Invocation guide',
  'P00 创作任务简报与缺口诊断': 'P00 Creative brief and gap diagnosis',
  'P01 素材净化与原创灵感卡': 'P01 Material cleanup and original idea cards',
  'P02 题材读者承诺与差异化': 'P02 Genre promises and differentiation',
  'P03 概念筛选与前提压力测试': 'P03 Concept selection and premise stress tests',
  'P04 事实边界与创作考证': 'P04 Fact boundaries and research',
  'P05 因果型世界构建与一致性': 'P05 Causal worldbuilding and consistency',
  'P06 人物动力关系与弧线': 'P06 Character drives, relationships, and arcs',
  'P07 冲突升级信息释放与复线': 'P07 Conflict, information, and subplots',
  'P08 结构模型选择与全书转折': 'P08 Structure models and major turns',
  'P09L 长篇卷级承诺复线与中段': 'P09L Volumes, subplots, and middles',
  'P09S 短篇单一效果压缩与结尾': 'P09S Single effect, compression, and endings',
  'P09R 连载阅读回报断点与生产': 'P09R Serial rewards, breaks, and production',
  'P10 章节功能场景转折与情绪': 'P10 Chapters, scene turns, and emotion',
  'P11 首章续写对白动作与叙述': 'P11 Openings, continuation, dialogue, and prose',
  'P12 章节记忆事实状态时间线与伏笔': 'P12 Memory, facts, states, timeline, foreshadowing',
  'P13 发展性编辑因果人物与结局': 'P13 Developmental editing',
  'P14 场景对白视角节奏与定向改写': 'P14 Targeted scene and prose revision',
  'P15 首章盲读期待兑现与贝塔模拟': 'P15 Blind reads, promises, and beta simulation',
  'P16 书名简介梗概标签与投稿': 'P16 Titles, blurbs, synopses, and submissions',
  'P17 运行复盘版本评测与 Prompt 生成': 'P17 Run review, evaluation, and Prompt generation',
  'C · 类型专项': 'C · Genre specialties',
  '推理：谜底线索误导与揭示': 'Mystery: solutions, clues, misdirection, reveals',
  '爱情：吸引阻力亲密与结局': 'Romance: attraction, resistance, intimacy, endings',
  '成长升级：能力资源挑战与代价': 'Progression: abilities, resources, challenges, costs',
  '历史小说：史实锚点与时代质感': 'Historical fiction: anchors and period texture',
  '科幻：新设定技术约束与后果': 'Science fiction: novums, constraints, consequences',
  '奇幻：魔法规则神话文化与奇观': 'Fantasy: magic, myth, culture, and wonder',
  '群像：多视角角色权重与信息拼图': 'Ensemble: viewpoints, weight, information',
  '现实文学：日常压力与开放意义': 'Literary realism: daily pressure and open meaning',
  '恐怖：威胁未知升级与余悸': 'Horror: threat, unknowns, escalation, aftereffects',
  '喜剧：反差误会升级与人物尊严': 'Comedy: contrast, misunderstanding, dignity',
  'D · 漫剧 Prompt 工程': 'D · Motion-comic Prompt engineering',
  '漫剧 Prompt 工程与质量规则': 'Engineering and quality rules',
  'D-01 逐章节摘要提取': 'D-01 Chapter summary extraction',
  'D-02 起承转合阶段划分': 'D-02 Four-stage structure segmentation',
  'D-03 情节点分组与集数分配': 'D-03 Plot grouping and episode allocation',
  'D-04 本集动态人物状态': 'D-04 Dynamic episode character states',
  'D-05 伏笔呼应与视觉物理连贯': 'D-05 Foreshadowing and physical continuity',
  'D-06 基于诊断结果的定向修正': 'D-06 Diagnosis-driven corrections',
  'D-07 小说素材到标准漫剧剧本': 'D-07 Fiction to motion-comic script',
  'D-08 标准剧本到 AIGC 分镜': 'D-08 Script to AIGC storyboards',
  'D-09 治愈系竖屏漫剧剧本': 'D-09 Comforting vertical motion-comic scripts',
  'D-10 漫剧时长逻辑角色与制作质检': 'D-10 Duration, logic, character, production QA',
  '项目动态': 'Project updates',
  '项目动态概览': 'Updates overview',
  '更新日志': 'Changelog',
  '版本、升级与兼容': 'Versions, upgrades, and compatibility',
  'Bug、功能与文档纠错反馈': 'Bugs, features, and doc corrections',
  '反馈中心': 'Feedback center',
  'Bug 报告': 'Bug report',
  '功能建议': 'Feature request',
  '文档纠错': 'Documentation correction',
  '历史归档': 'Historical archive',
  '归档说明': 'About the archive',
  '2026-05-28 功能全景指南': '2026-05-28 panoramic guide (Chinese)',
  '历史功能更新全文': 'Historical feature updates (Chinese)',
  '历史费用指南': 'Historical costs (Chinese)',
  '旧 Bug 收集': 'Old bug collection (Chinese)',
  '旧功能建议收集': 'Old feature requests (Chinese)',
  '知识库首页': 'Knowledge base',
  '回到官网': 'Official website',
  'GitHub': 'GitHub',
}
